### ISSUE TITLE
Implement option to allow custom SSL CAs to be uploaded

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3011]
### Actual behavior

Currently you can either install your custom ca certificates "the hacky way" or, on most parts, simply ignore the verification. While ignoring the verification works, it's imho bad, because you can never be sure that the remote part you're talking to is really the part you were planning to talk to.

### Expected behavior

We would like to make it easier and straight forward on how to add custom CA certificates for SSL verification for Zammad users. To help users, we thus will implement a new UI-Interface within admin settings -> Security to hold a new Tab "SSL / CA" which allows administrators to add one or more CA certificates to the Zammad installation.

This will help Zammad to verify self-signed certificates without big struggles. Also, this implemention will greatly help hosted customers, because self signed certificates and their ca can be checked easier and don't need hacky implementations that are not migration safe.

### Use Cases

As an administrator, 
- I want to be able to upload my custom CA certificates to Zammad so that they can be used for certificate validation. These certificates should be used in addition to the system certificates, in all places *where full SSL verification is already available* in Zammad.

### Technical Implementation

CA certificates should be stored in the DB and used at runtime, similar to the S/MIME certificate handling. No new shared folders, if possible.

Suggestion: See OpenSSL::SSL::SSLContext::DEFAULT_STORE for a starting point. We can add certificates to such a store at runtime and pass it to the SSL security context. This must be done in all relevant places where SSL is used, or we need to find a generic way to implement this.

Note that this is not about adding SSL verification in places that don't use it yet, as there is a separate task for that.

### Mockup

Wording needs to be improved, table can probably be similar to SMIME certificates management.

![Image](https://github.com/zammad/zammad/assets/211281/a3788151-2722-4244-ac61-6cb2ba25dfb1)

```[tasklist]
### Tasks
- [x] Testing strategy
- [x] Certificate management: back end, storage
- [x] Certificate management: middleware
- [x] Certificate management: front end
- [x] Certificate usage for connections
- [x] Align model with current smime certificates - DK/FL
- [x] Tests
```

**Comment by mgruner** [comment]
### Refinement 2023-06-27: Tasks
- create mockups for the management screen
- add management screen 
- make sure the uploaded CAs get used where full SSL verification is *already* in use
- this does not affect other places where SSL verification is not yet used - will be addressed soon in another task

**Comment by mgruner** [comment]
See `OpenSSL::SSL::SSLContext::DEFAULT_STORE` for a starting point. We can add certificates to such a store at runtime and pass it to the SSL security context. This must be done in all relevant places where SSL is used, or we need to find a generic way to implement this.
