### ISSUE TITLE
Automatic third-party account linking notification

### ISSUE THREAD

**Issue by KoJie** [zammad/zammad#4410]
### Infos:

* Used Zammad version: 5.3
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Actual Behaviour:
As an admin, I have no way to enable a notification for account linking.

As agent I don't get a notification via e-mail about a new account link of the own account with a third party login (e.g. SAML).

As customer I don't get a notification via e-mail about a new account link of the own account with a third party login (e.g. SAML).

### Desired Behaviour:
As an admin, I have the possibility to activate a notification for the automatic account linking.

As an agent, I receive a notification via e-mail when an automatic account linking with a third party login (e.g. SAML) has taken place.

As a customer, I receive a notification via e-mail when an automatic account linking with a third party login (e.g. SAML) has taken place.

As system notifications are sent automatically when an account is linked automatically

### ToDo:

- [x] Define notification template
- [x] Check the current configuration setting and decide if we are going to improve it or create a new one
- [x] Implement notification
- [x] Add and extend tests
- [x] Add possible translations in Weblate

**Comment by fliebe92** [comment]
-
