### ISSUE TITLE
SAML Single Logout

### ISSUE THREAD

**Issue by KoJie** [zammad/zammad#4412]
### Infos:

* Used Zammad version: 5.3
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Actual Behaviour:
As admin I cannot specify a SAML logout endpoint.

As system I do not execute a request to the SAML logout endpoint

### Desired Behaviour:
A SAML logout endpoint should be triggered (in addition) as soon as you press Logout in Zammad.

### ToDo:

- [x] Check if we need some more configuration in Keycloak (related Docker container)
- [x] Check SAML RFC for correct implementation
- [x] Check if we could improve the current form for SAML configuration in Zammad itself (certificate field)
- [x] Add invalid session handling for logout situations on IDP side.
- [x] Testing

**Comment by fliebe92** [comment]
-

**Comment by tschaefer** [comment]
We have to provide the following option to the **omniauth SAML provider**.

* `:idp_slo_service_url` - The URL to which the single logout request and response should
  be sent. This would be on the identity provider. Optional.
