### ISSUE TITLE
Missing rake task to fix json values migrated from maria/mysql to postgres

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#4431]
### Used Zammad Version

5.3

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]
- Database + version:  mariadb
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]

### Actual behaviour

- Migration does not convert the json values to the array structure of postgres. I think there is a rake task missing which will look up all values in the database and convert the json structures to array.

I attached a PoC how it could look like:

[fix_maria_migration.zip](https://github.com/zammad/zammad/files/10245529/fix_maria_migration.zip)

### Expected behaviour

- Migration should work.

https://docs.zammad.org/en/latest/appendix/migrate-to-postgresql.html

### Steps to reproduce the behaviour

Migrate from mysql/mariadb to postgres, but before create multi tree selects and fill up some tickets:

https://docs.zammad.org/en/latest/appendix/migrate-to-postgresql.html

### Support Ticket

Ticket#10115329

### I'm sure this is a bug and no feature request or a general question.

yes

### ToDo:

- [x] Investigate a post or pre pgloader solution
- [x] Decide and implement a solution
- [x] Update the current documentation
- [x] Adding a integration test of the database migration from mysql/mariadb to postgres

**Comment by rolfschmidt** [comment]
@MrGeneration Can you add a note to the documentation that the migration path is currently broken linked to this issue?

**Comment by MrGeneration** [comment]
That's entirely the wrong repository.
The PoC is not living here.

**Comment by MrGeneration** [comment]
After an internal heads up by @rolfschmidt I learned that this is something the migration script can't handle and thus needs a rake task.

**Comment by mgruner** [comment]
Alternative solution idea: maybe we could create a rake task that reads the DB before migration, and outputs [pgloader casting rules](https://pgloader.readthedocs.io/en/latest/ref/mysql.html?highlight=cast#mysql-database-casting-rules) which would perform the migration correctly in the first place.

**Comment by dvuckovic** [comment]
There are currently concerns regarding the performance of the PoC attached to this issue, since it uses `ActiveRecord::Migration` instances, creates new columns, migrates the data, drop, then rename the columns... Also, it's not clear if it would have additional side-effects, since it is supposed to be run in the application/Rails context. A benchmark with a large data set and both solutions in place (PoC vs `pgloader`) might try dispel these concerns, but it hasn't been tried yet.

Initial research into `pgloader` casting rules resulted in some findings:

* It doesn't look like `pgloader` provides a suitable transformation function for a JSON array into a PostgreSQL array which can be used as part of its `CAST` command (on the column type level.) We could not find an example either, and trying some stuff including expected DSL like `"text array"` didn't lead to meaningful results. This doesn't mean it's not supported, just that we could not identify it at this time.

* [An issue for `pgloader`](https://github.com/dimitri/pgloader/issues/881) with a similar problem provided a possible workaround via `AFTER LOAD DO` block, which can transform specific columns on specific tables only, but it does use a `translate` function which seems to work for our JSON => array use-case. (Note that this same function doesn't seem to be provided in the `CAST` context.) 

Here is a working example for `pgloader` post-processing block for one `multi_tree_select` column on the `tickets` table:

```
...
AFTER LOAD DO
    $$ alter table tickets alter column multi_tree_select type text[] using translate(multi_tree_select::text, '[]', '{}')::text[] $$
...
```

A proposed rake pre-task could try to prepare the complete `pgloader` script and include one line per affected column.

**Comment by mgruner** [comment]
@dvuckovic that's kindof what I hoped for. So I'm all for pursuing this further. It should be best to get the migration right in the first place.

Please note that @rolfschmidt included at least one column for this transformation which does not come from object attributes (IIRC `PublicLink`). We should try to include all candidates, of course.

**Comment by dvuckovic** [comment]
Another idea that just came to mind: it's possible to get all JSON columns in a MySQL database with one query.

```
mysql> select table_name, column_name from information_schema.columns where table_schema = 'zammad_development' and data_type = 'json';
+--------------+-------------------+
| table_name   | column_name       |
+--------------+-------------------+
| public_links | screen            |
| tickets      | multi_tree_select |
| tickets      | multi_select      |
+--------------+-------------------+
3 rows in set (0.00 sec)
```

However, it's still safer to go with the PoC approach since we are absolutely positive these columns are used only as simple JSON arrays.

**Comment by mgruner** [comment]
@dvuckovic plus, this would not work with MariaDB, as it does not have native json types.

Perhaps it would be a good idea to verify your solution also for MariaDB -> PG migration.

**Comment by dvuckovic** [comment]
@mgruner Correct, in MariaDB these columns are of `longtext` type.

I just verified that the same script works on MariaDB as well, columns are properly migrated to `array` type on PostgreSQL.

**Comment by dvuckovic** [comment]
For posterity: we did some reproduction of the original issue, by skipping `AFTER LOAD DO` statements in our test job. And the results are rather surprising!

On MySQL, the column will be left in `json` type on PostgreSQL (it still supports them!). While everything will still work as expected (the stored data is decoded/encoded correctly), the schema is definitely different than a regular PostgreSQL instance that was initialized from scratch.

On MariaDB, the column will be migrated to `text` type on PostgreSQL. This breaks the decoding of stored values, and while the system will still happily continue chugging on, the data does look corrupted. Just take a look how the frontend shows some of these multiselects:

![Image](https://user-images.githubusercontent.com/6049445/209136432-bfe873ab-85e6-4b77-8004-3e503f549b46.png)
![Image](https://user-images.githubusercontent.com/6049445/209136431-265ae272-c120-46f5-8689-4ba1e5cd091f.png)

Strictly speaking, this means the original issue is reproducible only on MariaDB backends. However, it's not clear if there would be some issues down the line, so we would still prefer the migration to `array` columns.

**Comment by MrGeneration** [comment]
> Strictly speaking, this means the original issue is reproducible only on MariaDB backends. However, it's not clear if there 
> would be some issues down the line, so we would still prefer the migration to array columns.

I am confused as I received this PR: 
https://github.com/zammad/zammad-documentation/pull/263

What is needed what is not?
Can we please clarify that before hand? I feel like I'm touching things without any use.

**Comment by dvuckovic** [comment]
@MrGeneration Please ignore my previous comment, it was just a minor finding during testing.

The documentation PR you linked to looks correct and the new command applies to both MySQL and MariaDB backends. With the fix in place, the migrated columns are always of the same data type (`ARRAY`), which is what you would expect.
