### ISSUE TITLE
OTRS migration from OTRS 6 imports all ticket articles as internal and with not correct article type

### ISSUE THREAD

**Issue by dominikklein** [zammad/zammad#4449]
### Used Zammad Version

5.4.x (develop)

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

The import from an OTRS 6 system creates all ticket articles as internal. Also when the articles were not internal on the OTRS side. Also the article type information is not correct after the import.

### Expected behaviour

The import from OTRS 6 should reflect the correct "internal" information and article type during the ticket article creation on Zammad's side.

### Steps to reproduce the behaviour

Example: [ticket.txt](https://github.com/zammad/zammad/files/10336262/ticket.txt)

- Create a ticket and articles (public and internal) inside of an OTRS 6 system.
- Start the import from OTRS 6.
- Check the created ticket articles afterward.

### I'm sure this is a bug and no feature request or a general question.

yes

### ToDo

- [ ] Check changed information from OTRS 5 -> 6
- [ ] Implement a solution which is working for OTRS 6 and lower versions.
- [ ] Extend existing import tests.

**Comment by dominikklein** [comment]
This happens, because the `ArticleType` is no longer present in the article payload during the import.

**Comment by dominikklein** [comment]
Was a problem with a not updated Znuny4Migrator-Package on our internal CI-Docker-Image.
