### ISSUE TITLE
Support LDAP interfaces that always need authentication (e.g. OKTA LDAP)

### ISSUE THREAD

**Issue by dominikklein** [zammad/zammad#4471]
### Summary (What)

Zammads LDAP integration does not work with modern LDAP interfaces, e.g. Okta LDAP.

### Actual behavior

At the moment the first connection of a new LDAP source during the setup wizard is done without authentication (no possibility to add authentication information in the first wizard screen). This fails on the LDAP interface which needs always authentication.

### Expected behavior

It should be possible to add a new LDAP source that needs always authentication (as defined in RFC 4513).
However, the existing LDAP configurations should still be working after we implement the new behavior.

### Technical Information

`>can't connect to '[dev-48672522.ldap.okta.com](http://dev-48672522.ldap.okta.com/)' can't bind to [dev-48672522.ldap.okta.com](http://dev-48672522.ldap.okta.com/)', 53, unwilling to perform<`

The reason for this error is that e.g. Okta LDAP is enforcing RFC 4513 which states:
`Additionally, Servers SHOULD by default fail Unauthenticated Bind requests with a resultCode of unwillingToPerform.`

### Technical Implementation Idea

The idea is to add the possibility that the `Base DN`, `Bind User`, and `Base Password` can be entered without a first "connection" check which runs without the credentials.
It should be possible to check the first resultCode to decide how the wizard should go forward (prefill "Base DN" or manually enter the field data => for this situation the field type needs to be changed from select to text).

```[tasklist]
### Tasks
- [x] Create test ldap (for manual testing) with not allowed anonymous bind
- [x] Change UI to support the plain text fields for authentication
- [x] Check if backend need to be changed
- [x] Add test cases for new situation
```
