### ISSUE TITLE
Navigation sidebar does not collapse on tablet devices

### ISSUE THREAD

**Issue by dvuckovic** [zammad/zammad#4473]
### Used Zammad Version

5.3

### Environment

- Installation method: any
- Operating system: any
- Database + version: any
- Elasticsearch version: any
- Browser + version: Chrome v109.0.5414.83 & Safari 16 @ iPadOS v16

### Actual behaviour

The navigation sidebar cannot be collapsed on tablet devices which have a horizontal resolution of more than `767px`.

<img width="1023" alt="Screenshot 2023-01-25 at 12 28 44" src="https://user-images.githubusercontent.com/6049445/214563545-8088b3e6-782d-4da3-b6ae-efc7ddc251f1.png">

### Expected behaviour

The navigation sidebar should be collapsible on devices with higher resolutions, but perhaps on demand and not just automatically.

<img width="747" alt="Screenshot 2023-01-25 at 12 28 56" src="https://user-images.githubusercontent.com/6049445/214563564-3970b6b1-c3be-424c-93ab-d1aed1160ae6.png">

### Steps to reproduce the behaviour

1. Visit Zammad instance on a touch device (i.e. a tablet) in horizontal orientiation.
2. Note that the navigation sidebar is not collapsed and cannot be collapsed unless you orient the device into portrait mode (sometimes not even then).

Most of the tablet devices currently on the market have a horizontal resolution of more than `767px` which is break point for the automatic collapsing of the navigation sidebar. Hence, the navigation sidebar takes too much of the screen real estate, making it very difficult to work with views that contain a lot of data (i.e. tables).

Consider adding a gesture (i.e. a right swipe) that would explicitly collapse the navigation sidebar if the user needs it.

### Support Ticket

Ticket#10118758

### I'm sure this is a bug and no feature request or a general question.

yes

```[tasklist]
### Tasks

- [x] Implement an explicit navbar collapse button visible on mobile/tablet devices (@mantas)
- [x] Fix popover display on touch screens (@mantas)
- [x] Improve behavior of the search field on touch screens (@mantas)
- [x] Clarify the proposed design of the collapse button (@dvuckovic)
- [x] Provide double arrow icons (@dvuckovic)
- [x] Fix counter alignment next to the logo in mobile mode (@dvuckovic)
- [x] Align the solution with approved design (@mantas)
- [x] Extend tests (@mantas)
```

**Comment by dvuckovic** [comment]
The styles for a "collapsed" navigation bar already exist in form of phone-specific styles. In addition to media queries we would only need to apply them in case the navigation is considered collapsed.

Next, a swipe gesture can be determined via `touchstart`, `touchmove` and `touchup` events, in case the horizontal difference in pixels since the touch event start has a value. If this difference is positive, the gesture can be considered as a right swipe, otherwise it would be a left swipe.

Finally, we could toggle add a class on the app container depending on the swipe direction, in order to collapse or expand the navigation bar explicitly. The state may be stored in browser's `localStorage`, since the behavior should be restored on subsequent visits (but only on the same device).

Since the touch events are not supported by desktop computers, we can be sure this behavior will kick in only on touch devices (i.e. tablets, phones).

**Comment by dvuckovic** [comment]
Internal testing with swipe gestures proved this to be a very unstable solution. Gestures are regularly interfering with the scrolling, and the existence of many interactive elements in the navbar area do not help with accidental touches.

Alternative proposal is to provide an explicit expand/collapse button on top of the navbar, and make this visible only for mobile/tablet devices. This would also make the current mechanism for expanding the nabar on mouse "hover" event obsolete. (Hover is notoriously difficult to hook into on touch devices and current behavior is very erratic.)

Proposed collapsed look:

![Screen Shot 2023-03-21 at 11 04 49](https://user-images.githubusercontent.com/6049445/226589640-4dbd3f87-497a-4c13-8ba4-de99a8ab2bdf.png)

Proposed expanded look:

![Screen Shot 2023-03-21 at 11 06 55](https://user-images.githubusercontent.com/6049445/226589696-3254b66f-4db6-43e4-aeaa-b7f3bba4f02a.png)

**Comment by mrflix** [comment]
I think it's a good solution! I was wondering where I saw a similar button and it's in gitlab. There the toggle button is placed at the bottom. I think it's fine that our button is at the top.

> Since the touch events are not supported by desktop computers, we can be sure this behavior will kick in only on touch devices (i.e. tablets, phones).

Although you dropped the gesture: keep in mind that there are desktop computers with touch support out there. It's very tricky to detect only tablets. But it probably wouldn't be a problem to support the gesture in touch desktops too.

**Comment by dvuckovic** [comment]
@mrflix Thanks for your feedback!

For good measure, here is an option with the button on the bottom:

![Screen Shot 2023-03-21 at 14 50 24](https://user-images.githubusercontent.com/6049445/226646183-c64776f1-62bb-4c02-b594-cac8f1867e68.png)

![Screen Shot 2023-03-21 at 14 51 24](https://user-images.githubusercontent.com/6049445/226646196-5def588d-c897-4c10-9524-140d71e8e556.png)

**Comment by KoJie** [comment]
yeah, the second solution looks also great for me - thus the 🕊️ is still in it's place 👍
