### ISSUE TITLE
Pre-defined webhooks ready to use

### ISSUE THREAD

**Issue by fliebe92** [zammad/zammad#4482]
### Actual behavior:

It is not possible to select from a list of pre-defined webhooks (e.g. Slack).

### Expected behavior:

As an admin, I want to select pre-defined webhooks (e.g. Slack) that should show an easily usable UI.

These pre-defined webhooks can be selected for the creation of a new webhook. The payload is rather static, but some custom values can be set by using the provided UI.

For this to work, the current webhook implementation is going to be extended:

- By creating a new webhook, it is possible to select pre-defined webhooks from a list.
- By selecting a pre-defined webhook, the fields are pre-populated with values loaded from the pre-defined webhook.
  - This is going to work like a template. If needed, it is possible to overwrite some values.
  - ~~It is possible to expand the read-only payload field.~~ Custom payload field provides a way to further customize the data structure to admin's liking.

Optional:

~~- Create a trigger(s) together with pre-defined webhooks.~~
(We will show a link on the documentation page.)

### Technical Implementation/Questions:

- Is it needed to overhaul the UI of the webhook configuration for this?
- Do we need a reset functionality?
- The pre-defined webhooks provide a simple UI with just regular input/select fields.
  - We do not want to provide a complex UI with nested structures etc. for now.

#### Possible Solution:

- New "Config/Setting" column in the webhook table, which holds the information of a pre-defined webhook.
- Pre-Defined Webhook, can be a data structure inside a ruby class, which holds the needed information (Name, Fields (can be similar like for settings?), Custom-Payload).
- Inside the Custom-Payload the values from the Pre-Defined Webhook fields can be "placed" (e.g. `webhook.setting.channel`). This will then be replaced with the current value from the webhook table (another possibility would be that the value from the form will directly be added inside the custom payload).
- New webhook controller endpoint which returns the current pre-defined webhooks (with the needed information).
- 
### Mockups

Creation of a pre-defined webhook:
![Screen Shot 2023-04-18 at 10 33 03](https://user-images.githubusercontent.com/6049445/232736314-78e8ec9f-d677-4b6e-b6c9-b4c25571f06f.png)

Selection of a pre-defined webhook:
![Screen Shot 2023-04-18 at 10 33 19](https://user-images.githubusercontent.com/6049445/232736377-695a54f6-2914-4f81-80e1-acf944192cf0.png)

Injected pre-defined webhook fields:
![Screen Shot 2023-04-18 at 10 33 29](https://user-images.githubusercontent.com/6049445/232736426-c6b4261d-ff8e-4e4f-8f39-f1f78d3afdd9.png)

With customized payload:
![Screen Shot 2023-04-18 at 10 33 43](https://user-images.githubusercontent.com/6049445/232736474-45ab14a0-8ef3-4cfe-a6d9-202392ec6983.png)

Example payload screen:
![Screen Shot 2023-04-18 at 10 33 13](https://user-images.githubusercontent.com/6049445/232736568-e65ff9e6-fb69-43d0-9c45-43deabdcd2f9.png)

```[tasklist]
### Tasks
- [x] Add a new database column inside the webhook table to save the settings of the pre-defined webhook.
- [x] Create the pre-defined Webhook class layer inside the backend.
- [x] Add a new webhook controller endpoint to return the pre-defined webhooks.
- [x] Add replacement of webhook settings inside the custom payload.
- [x] Usage of new webhook controller endpoint and output of pre-defined webhooks in the frontend.
- [x] Output pre-defined webhook fields inside the add/edit webhook dialog
- [x] Make custom payload read-only for pre-defined webhooks (_DV: we actually don't want this_)
- [x] Add 3 static Mattermost webhook fields to the replacements endpoint
- [x] Testing
- [x] Add customized payload field and associated behavior
- [x] Review
```

**Comment by dominikklein** [comment]
Slack Payload:

```
{
   "channel": "ci-zammad",
   "username": "zammad_agent",
   "icon_url": "https://zammad.com/assets/images/logo-200x200.png",
   "mrkdwn": true,
   "text": "# #{ticket.title}",
   "attachments":[
      {
         "text":"#{notification}",
         "mrkdwn_in":[
            "text"
         ],
         "color":"#{ticket.current_state_color}"
      }
   ]
}
```

**Comment by dominikklein** [comment]
Microsoft Teams Payload (some formatting, coloring needs to be checked/improved for our default payload):

```
{  
   "type":"message",  
   "attachments":[  
      {  
         "contentType":"application/vnd.microsoft.card.adaptive",  
         "contentUrl":null,  
         "content":{  
            "$schema":"http://adaptivecards.io/schemas/adaptive-card.json",  
            "type":"AdaptiveCard",  
            "version":"1.2",  
            "body":[  
                {  
                "type": "TextBlock",  
                "text": "#{ticket.title}"  
                },  
                {  
                "type": "TextBlock",  
                "text": "#{notification}"      
                }  
            ]  
         }  
      }  
   ]  
}
```

**Comment by dvuckovic** [comment]
Revised behavior regarding customized payloads (proposal):

* A new switch with label **Custom Payload** is rendered above the existing custom payload field.
* When turned off, custom payload field is hidden entirely from the screen.
* When turned on, custom payload field is shown below.
* The existing collapsed behavior of the custom payload field is changed, its label is hidden as the switch functions as one.

Special behavior for pre-defined webhooks:

* When visible, custom payload field is pre-populated with the pre-defined webhook custom payload, allowing admins to further customize them.
* When **Custom Payload** switch is turned off, custom payload field will be blanked on save.
* Webhooks with blanked custom payload field will inherit from the original pre-defined webhook custom payload at the time of firing.
* New switch will also allow for easier migration of non-customized pre-defined webhooks, if at any point the need arises.
* It would not be possible to change the pre-defined webhook dropdown, once a webhook has been created (disabled state).

**Comment by dvuckovic** [comment]
@KoJie @martini Proposal for the hint below the custom payload field:

![Image](https://user-images.githubusercontent.com/6049445/233949776-dc18cec4-689e-4378-8f2e-3cb39b3c1224.png)

The hint would collapse when the switch is turned off, of course:

![Image](https://user-images.githubusercontent.com/6049445/233949874-a4b5a27f-2bcc-43f2-938c-3e025757db79.png)

What do you think?

**Comment by martini** [comment]
I'm fine with it.
