### ISSUE TITLE
Custom payload for webhooks

### ISSUE THREAD

**Issue by fliebe92** [zammad/zammad#4483]
### Actual behavior:

It is not possible to define the payload in a webhook to my personal needs. A static ticket JSON structure is always used.

### Expected behavior:

The current way of the webhooks should work like before. In addition to this, it should be possible to define custom payloads with mapped ticket values as shown in the example below:

```json
{
  "type": "message",
  "data": {
    "title": "#{ticket.title}"
    "sender": "#{current_user.fullname}"
  }
}
```

The custom payload field is not visible by default. If you want to use a custom payload, you need to expand the custom payload section in the configuration screen.

The custom payload is checked to be a valid JSON structure before saving.

Nice to have:

- JSON syntax highlighting
- Variable suggestions + auto-completion

Advanced features:

- JSON auto-formatting

### Technical Implementation/Questions:

- How to implement the custom payload field?
  - Should it be a simple `text area` in the beginning?
  - Do we have a simple solution in the jQuery context to provide a modern field?
- What else is needed to replace the current Slack integration (https://api.slack.com/messaging/webhooks)
  - `NotificationFactory::Slack` seems to be used in the Slack integration (for example, see `app/views/slack/ticket_create/en.md.erb`) / Generic solution of notification factory usage.
    - `human_changes` should be available for used NotificationFactory
  - Check for ticket updates without human changes? https://github.com/zammad/zammad/blob/414c111ae6f93ff7f95ab02ce3730ecdc9f7e21e/app/models/transaction/slack.rb#L57
  - Check to ignore ticket updates for system articles.
  - Remember already triggered slack call or not relevant in a new webhook context: https://github.com/zammad/zammad/blob/414c111ae6f93ff7f95ab02ce3730ecdc9f7e21e/app/models/transaction/slack.rb#L118-L134
  - Solution for current ticket status color: https://github.com/zammad/zammad/blob/414c111ae6f93ff7f95ab02ce3730ecdc9f7e21e/app/models/transaction/slack.rb#L100-L113 Maybe some "fixed" mapping variable which can be used (like we need for the notification factory).
  - Check the current notification templates, we should implement an "optional" article body output (maybe with an additional option that can be selected) **-> When this is too much effort it should be moved to a follow-up task.**

The trigger needs to provide all necessary data/objects for the custom payload. The variables in the custom payload need to be replaced with this information. We need to make sure that the replaced values are not going to break the JSON structure.

### Mockups:

Maybe instead of "Payload" we should use "Customize payload"

![customize-payload-collapsed](https://user-images.githubusercontent.com/5445094/218458696-de31c311-f176-4490-b381-3f15dbfd578c.png)

![customize-payload-expand](https://user-images.githubusercontent.com/5445094/218458742-83941502-d48e-4802-80ae-1829f9507196.png)

```[tasklist]
### Tasks
- [x] FL: Possibility to save a custom payload inside the webhooks
- [x] DK: Add a new simple custom payload field in the UI (and collapse/expand possibility)
- [x] TS: Variable replacement when a payload is triggered
- [x] DK/FL: Add custom validation method for forms
- [x] DK/FL: Generic solution to detect human_changes
- [x] FL: Add new `current_state_color` method to `Ticket` class
- [x] FL: NotificationFactory-Handling
- [x] FL/DK: Switch human_changes fallback from user_id(1) to a generic solution
- [x] CLARIFY: Trigger extension - executing of triggers also without field updates from current conditions
- [x] DK: Show custom payload field in UI expanded, when it's filled
- [x] Add slack integration test which uses webhooks.
```

**Comment by tschaefer** [comment]
For future enhancement, report semantic issues to the creator of the webhook. e.g. **No such ticket attribute `topic` at line 55.**

**Comment by KoJie** [comment]
There was a question whether the article body should be sent along, because in some cases this can lead to very long message threads.
I checked for usecases and learned that the article body is elementary important for many user in order to better assess the notification. On the other hand, there is the valid use case that the body must not be sent at all, because e.g. sensitive content should not be displayed. 
Therefore, it should be possible to map both use cases by selecting whether the body is sent or not.
