### ISSUE TITLE
HTTP BasicAuth for Webhooks 

### ISSUE THREAD

**Issue by dominikklein** [zammad/zammad#4510]
### Used Zammad Version

5.4.x (develop)

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

Currently, it's not possible to use `BasicAuth` inside the webhook configuration.

### Expected behaviour

It should be possible to save a username and password (optional) for the `BasicAuth` inside the webhook configuration.

### Support Ticket

Ticket#10115525

### I'm sure this is a bug and no feature request or a general question.

no

```[tasklist]
## Tasks
- [x] Add a migration for HTTP BasicAuth username and password fields
- [x] Implement back end logic and tests
- [x] Add fields to the UI
- [x] Review
```
