### ISSUE TITLE
Support title and body in core workflow actions

### ISSUE THREAD

**Issue by dominikklein** [zammad/zammad#4519]
### Used Zammad Version

5.4.x (develop)

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

It's not possible to use the ticket title and article body in the core workflow actions. So it's for example not possible to prefill the ticket title with a default value under defined conditions.

### Expected behaviour

It should be possible to define/configure the following actions for the ticket title and article body inside the core workflow actions:

- read-only / changeable (`set readonly` / `unset readonly`)
- set a value to the field (`fill in`)
- set an empty value to the field (`fill in empty`)

Currently, the prefill of the article body will not include attachments or inline images.

### Support Ticket

Ticket#10120537

### I'm sure this is a bug and no feature request or a general question.

no

```[tasklist]
### Tasks
- [x] DESKTOP | Implement usage of title + body in the core workflow admin interface.
- [x] DESKTOP | Improve desktop view to handle title + body when it's used inside a workflow.
- [x] DESKTOP | Refactor show hide of the secondary organization id to core workflow.
- [x] DESKTOP | Add tests for the title or body usage in core workflow.
- [x] MOBILE | Check if the mobile view is working as expected when title + body is used inside a workflow.
- [x] MOBILE | Align secondary organization handling and tests (now a core workflow instead of frontend).
- [x] MOBILE | Add tests for the title or body usage in core workflow.
```
