### ISSUE TITLE
Time Accounting Types

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#4533]
### Infos:

- Used Zammad version:
- Installation method (source, package, ..):
- Operating system:
- Database + version:
- Elasticsearch version:
- Browser + version:

### Summary (What)

The ticket time accounting should be extended with the possibility to add created types to structure different ticket time accounting entries together (e.g. in the time accounting activity report). For example time accounting entries from a ticket that are relevant to a "Billing" type.

### Expected behaviour:

**As an admin...**
- I would like to be able to enter time accounting types (in our case, 4 types).
- I want to activate / inactivate the selection of types.
- I can define a Time Accounting Type as default, which is preselected in each case (if no default is selected, the agent must select one).
- I can read out the time accounting types via API.
- I can see the types in the **By Activity** time accounting report

**REST-API...**
- I can use the missing API for Time Accounting (index, show, create, update (admin), destroy (admin)) and it should be possible to read this per ticket.

**As an Agent...**
- Can I select the time accounting types in a dropdown during the input in the time recording?

**As a customer...**
- I have no requirement.

#### Deletion of Types
A simple active flag like in other objects will solve it easily and there is no need to delete them.

From a backward compatibility standpoint, we also can allow the deletion of the types and support an empty type for the time accounting. Then we could clear the type for the time accountings on deletion and everything would be fine as well. The old time accounting entries won't have a type anyway.

![Screen Shot 2023-06-12 at 17 23 05](https://github.com/zammad/zammad/assets/6049445/f8365b35-976a-4937-8445-7ce6e3b5f612)

![Screen Shot 2023-06-12 at 17 23 58](https://github.com/zammad/zammad/assets/6049445/1534a42c-eddc-4ad1-98ec-2b0b17a2e28b)

![Screen Shot 2023-06-12 at 17 20 39](https://github.com/zammad/zammad/assets/6049445/1d84f5e9-388d-42ef-936c-569e6f9ad75e)

<img width="215" alt="Screenshot 2023-06-12 at 17 26 09" src="https://github.com/zammad/zammad/assets/6049445/bb5fe709-ce01-46bc-853c-619f285e4aa1">
<img width="190" alt="Screenshot 2023-06-12 at 17 26 35" src="https://github.com/zammad/zammad/assets/6049445/3d63370e-65ed-4bd5-8672-60031193cf59">

```[tasklist]
### Tasks
- [x] New Time-Accounting-Type model inside backend - MM
- [x] Handling of Time-Accounting-Types in admin area (create/update/delete?) - MM
- [x] New setting for general selection of time accounting types - MM
- [x] Time-Accounting-Type default handling (without a default, the field should be empty) - MM
- [x] Extend time accounting model to support a optional time accunting type - DK
- [x] Extend current Controller-API to save the selected time accounting type - DK
- [x] Selection of time accounting type in ticket context (dialog) -  DV
- [x] Output of the new time accounting type in "By activity" table and export - DV
- [x] TimeAccounting REST-API extensions - DK/MM
- [x] Revert everything about the `input[type=number]` change - DV
- [x] Add a switch setting that enables the time accounting type selection & inclusion in reports - DV
- [x] Add `Unset default` action to activity types - DV
- [x] Tests - MM/DV
- [x] Move handling of requests for accounted time tables under the new tab - MM
- [x] Review
```

**Comment by KoJie** [comment]
one concern that came up: what would happen when a type will be deleted?
The idea of the dev-team is that it should not be possible to delete types (analogous to the behavior with e.g. groups) and it should only be possible to deactivate them. Therefore the type is no longer visible/selectable for the agent but in the reporting the deactivated type is still displayed.

**Comment by rolfschmidt** [comment]
> one concern that came up: what would happen when a type will be deleted? The idea of the dev-team is that it should not be possible to delete types (analogous to the behavior with e.g. groups) and it should only be possible to deactivate them. Therefore the type is no longer visible/selectable for the agent but in the reporting the deactivated type is still displayed.

This not really a blocker. A simple active flag like in other objects will solve it easily and there is no need to delete them.

From a backward compatibility standpoint, we also can allow deletion of the types and support an empty type for the time accounting. Then we could clear the type for the time accountings on deletion and everything would be fine as well. Old time accountings won't have a type anyway.

**Comment by FreeMinded** [comment]
Looks very good! One question though, will there be a way for the agent to change a time accounting entry (in case of entry error)?

**Comment by martini** [comment]
> Looks very good! One question though, will there be a way for the agent to change a time accounting entry (in case of entry error)?

In this case I see problems, because reports - depending on when they are executed - can be different. 

My suggestion here would be the possibility of "-" bookings/entries. Then it would also be transparent to all.

Just my 2 cents.

**Comment by rolfschmidt** [comment]
![image](https://github.com/zammad/zammad/assets/5445062/9eedd4d3-17eb-4024-8d91-a27f411ec8fe)

![image](https://github.com/zammad/zammad/assets/5445062/9830fb0b-0b31-4747-b910-4019f7b33185)

**Comment by silvermind** [comment]
nice work 👍 one thing what was unfortunately missing our specs, was

**REST-API.**
get the time_accounting entires filtered by a date range (or a given day, similar to the reporting api which allowed year and month filters)

e.g:
```
/api/v1/time_accountings?from_date=2023-06-01&to_date=2023-06-19
/api/v1/time_accountings?from_date=2023-06-19&to_date=2023-06-19
```

NOTE: not sure if the filter should be required, as this call without any filter otherwise would return all existing time accountings in the system.(with pagging?)
`/api/v1/time_accountings`


best regards
Severin
