### ISSUE TITLE
VIP state for organizations

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#4543]
# What

In some situations, the organization is more important/critical than another organization and the tickets should be handled with a higher priority.

For example, you have B2B and one organization has a special contract and this should lead to faster handling of the tickets.

# Specification

### As Admin...

- I have the possibility to set a VIP flag at the organization (or secondary).

### As an User...

- There will be no difference in the VIP-Output.

**in the user profile...**

- I see a golden crown in the user profile when my user is VIP only.
- Organizations in User Profile will get a popover (like already existing in other places, e.g. search result item in the taskbar). The Crown (or other organization VIP indicator) will not be shown in the profile itself.

**in the organization profile...**

- I see a silver crown in the organization profile when the **organization** is VIP only.

![253004104-b4475e4e-d78a-427a-a169-53b9bd8f30b3](https://github.com/zammad/zammad/assets/26020836/db56b576-6ff5-452a-ac15-02115c15ca9b)

**in the ticket context...**

- TicketZoom header will display organization icon (if organization is present). This organization icon may have silver crown if the organization is VIP.

![253004752-0fbe96d2-90ec-4e4f-ad69-1e61037b67e9](https://github.com/zammad/zammad/assets/26020836/0583310f-0bda-4068-8185-aa697d3750d9)

**in the ticket create...**
- the customer and organization VIP status will be shown in their sidebars.

**in general...**

- Organization popover will include VIP state.
- User-Avatars in ticket watchers, notifications, bulk drag & drop and other views stay as-is.

-------

```[tasklist]
### ToDos
- [x] Add new `crown-silver` icon for both Desktop app and Mobile View - DV
- [x] Re-apply database changes (VIP flag for organizations + object manager attribute) - DV
- [x] GraphQL: Update organization attributes with the new VIP flag - DV
- [x] GraphQL: Update organization type with the new VIP flag - DV
- [x] Desktop app: Extend organization model with the new VIP flag - DV
- [x] Desktop app: Add base avatar base function to the organization model - DV
- [x] Desktop app: Add background organization avatar to the ticket zoom header - DV
- [x] Desktop app: Fix update of the avatar in the organization profile on model changes - DV
- [x] Desktop app: Fix style of user avatar when clickable - DV
- [x] Desktop app: Add popover for organization in user profile - DK
- [x] Tests - DV
- [x] Review
```

**Comment by martini** [comment]
My thought for a product implementation: The VIP flag should only be applied/shown at Org level and should also only be evaluated for triggers/schedulers at Org level.

Usecase: A customer (not vip) has the primary org (not vip) and a ticket where the customer (not vip) but a secondary org (with vip) is set. 

-> In future, the display of the customer (e.g. also in popovers) would always have to be made depending on the ticket. This is difficult IMO. And can confuse the user.

**Comment by dominikklein** [comment]
When I understood Rolf correctly the idea was to think not from a ticket perspective it should be a global perspective. So when the user is in at least one "VIP"-Organization, it's a VIP user.

**Comment by KoJie** [comment]
If you simply give every agent of an organization the VIP flag, you will again have usecases where the organization is VIP but it should still only be possible to give VIP status to certain agents - especially regarding the secondary-organizations. I have the feeling that we should find out more about the usecases here, so that we hit the nerve of many users.

That's why I have a few more questions regarding the usecases (maybe @YetAnotherGerrit can help here aswell?):

1. Is it only about the automatically passing of the VIP-flag for users when the organization becomes VIP? Because in this case you could use the REST-API, can't you?
2. What kind of system/ customer-usecase would benefit from this feature in general?
3. Or is this also the usecase that needs to be mapped?
One ticket is more important than others, therefore it should be worked on primarily > so far this is only mapped via the VIP status of the user. Now a ticket should be even more important, because the organization behind is also flagged as VIP ==> this makes the ticket even more important than just the VIP status of the user.

**Comment by martini** [comment]
> When I understood Rolf correctly the idea was to think not from a ticket perspective it should be a global perspective. So when the user is in at least one "VIP"-Organization, it's a VIP user.

In the usecase (software vendor like Zammad. Org VIP shows if Org has a support contract. -> open a ticket as agent): customer of ticket (no VIP), org of ticket (no VIP), another org or prim. org of customer (which is not the org of the ticket - with VIP) shows the customer of the ticket as VIP? This is IMO misleading (the agent may understood that it is ticket where the customer has a support contract).

I want to point out. A dedicated vip flag on organization only sounds good.

**Comment by YetAnotherGerrit** [comment]
As I said before, I would prefer to not transfer overwrite the User.vip-attribute by the Organisation.vip-attribute. But use a silver crown for Organisation.vip. All users who are members of VIP-organisation will get a silver crown, and if they are VIP on user-level they will get a gold crown. If you make the silver-crown slightly larger than the gold-crown you could even see a silver-outline for the gold crown.

**Comment by rolfschmidt** [comment]
> As I said before, I would prefer to not transfer overwrite the User.vip-attribute by the Organisation.vip-attribute. But use a silver crown for Organisation.vip. All users who are members of VIP-organisation will not get a silver crown, and if they are VIP on user-level they will get a gold crown. If you make the silver-crown slightly larger than the gold-crown you could even see a silver-outline for the gold crown.

@KoJie wants this solution in the core and asked me to discuss this with the customer. I will contact the customer and discuss this approach.

**Comment by rolfschmidt** [comment]
see https://github.com/zammad/zammad/issues/4543#issue-1643726683

**Comment by martini** [comment]
> As I said before, I would prefer to not transfer overwrite the User.vip-attribute by the Organisation.vip-attribute. But use a silver crown for Organisation.vip. All users who are members of VIP-organisation will not get a silver crown, and if they are VIP on user-level they will get a gold crown. If you make the silver-crown slightly larger than the gold-crown you could even see a silver-outline for the gold crown. 

I like this idea. But in addtion in case of viewing a ticket as agent (e. g. in order to start working on it) it is important for the agent to see clearly if this dedicated ticket is related directly to a VIP-element of an customer or organization of the ticket. If the ticket is not related to any VIP-element, then also not gray crown should be shown on customer user (IMO it's confusing the agent). Or at least show that this ticket is not related to any VIP-element directly.

I think I have to share my usecase which I have in mind: 

Zammad is placed in a payroll service provider. There are the following roles:

a) Agent (solves problem)
b) Customer - Actual company (which has payrolls/tickets about payrolls issues) 1:1 organisation
c) Customer - tax consultant (has access to many organisations of his customers who have tickets in the payroll office) 1:n organisations

**Comment by rolfschmidt** [comment]
> > As I said before, I would prefer to not transfer overwrite the User.vip-attribute by the Organisation.vip-attribute. But use a silver crown for Organisation.vip. All users who are members of VIP-organisation will not get a silver crown, and if they are VIP on user-level they will get a gold crown. If you make the silver-crown slightly larger than the gold-crown you could even see a silver-outline for the gold crown.
> 
> I like this idea. But in addtion in case of viewing a ticket as agent (e. g. in order to start working on it) it is important for the agent to see clearly if this dedicated ticket is related directly to a VIP-element of an customer or organization of the ticket. If the ticket is not related to any VIP-element, then also not gray crown should be shown on customer user (IMO it's confusing the agent). Or at least show that this ticket is not related to any VIP-element directly.
> 
> I think I have to share my usecase which I have in mind:
> 
> Zammad is placed in a payroll service provider. There are the following roles:
> 
> a) Agent (solves problem) b) Customer - Actual company (which has payrolls/tickets about payrolls issues) 1:1 organisation c) Customer - tax consultant (has access to many organisations of his customers who have tickets in the payroll office) 1:n organisations

I added your wishes to the specs thx! (meeting 2023-03-28 JK+RS+ME)

**Comment by KoJie** [comment]
for the start we decided to go with version D:


![Image](https://github.com/zammad/zammad/assets/22768032/e0d39808-8c83-401b-83b2-0855cec9531c)

**Comment by rolfschmidt** [comment]
I tried to explain it a little different, so it is exactly clear how the behaviour is in the ticket zoom as asked @dominikklein. But in general it is the same, as in the top. If you have questions, please ask. I personally don't understand what is unclear with the description, so I'm having a hard time to explain.

## Specification

**in the ticket zoom...**

All VIP icons of all users shown in the ticket zoom regard these rules:

- I see a golden crown for the user if the user is VIP only.
- I see a silver crown if the user is a member of the ticket.organization and the ticket.organization is VIP only.
- I see a golden+silver mixed when my user is VIP and the user is member of the ticket organization and the ticket organization is VIP too.

**in the user profile...**

- I see a golden crown in the user profile when my user is VIP only.
- I see a silver crown in the user profile when one of the user's organizations is VIP.
- I see a golden+silver mixed when one of the user's organizations is VIP and my user is VIP too.

**in the organization profile...**

- I see a silver crown in the organization profile when the organization is VIP only.

**Comment by mantas** [comment]
@KoJie I'd like to confirm following bits:

**Notifications list**

![Screenshot 2023-07-05 at 00 13 30](https://github.com/zammad/zammad/assets/36944/9ce48565-3028-4b54-a977-b20750bc7fbf)

I assume this should show crowns in ticket context?

**Drag & Drop bulk assignment**

![Screenshot 2023-07-05 at 00 12 09](https://github.com/zammad/zammad/assets/36944/db6980c7-575e-48fc-b452-19f494682ddf)

This is shown when dragging multiple tickets in overviews. It feels in the middle of global and ticket context. There're tickets involved, but it's multiple tickets. So I guess it should be global context instead?

**Users in Organization sidebar in _Create_ Ticket view**

Crown would be calculated assuming Ticket-to-be organization by taking customer-to-be primary organzation. Is that correct?

**Comment by mantas** [comment]
Notes from refinment on 2023-07-11:

- Users and organizations have separate crowns. No split crown.

- TicketZoom header will display organization icon (if organization is present). This organization icon may have silver crown if the organization is VIP.

- TicketZoom organization and customer sidebars would show crowns when either is VIP.

- Organization popover will include VIP state.

- Organizations in User Profile will get a popover. Crown (or other organization VIP indicator) will not be shown in the profile itself.

- TicketCreate will show customer and organization VIP status in their sidebars.

- Ticket watchers, notifications, bulk drag & drop and other views stay as-is.

**Comment by dvuckovic** [comment]
Updated mockups below.

## Ticket Zoom

![Ticket Zoom](https://github.com/zammad/zammad/assets/6049445/0fbe96d2-90ec-4e4f-ad69-1e61037b67e9)

## Organization Profile

![Organization Profile](https://github.com/zammad/zammad/assets/6049445/b4475e4e-d78a-427a-a169-53b9bd8f30b3)
