### ISSUE TITLE
SAML request signing / encrypting

### ISSUE THREAD

**Issue by tschaefer** [zammad/zammad#4558]
### Summary (What)

The communication between Zammad and e.g. Keycloak is not secure enough.

### Actual behavior

The current implementation of SAML within Zammad is missing the possibility of signing or encrypting any request.

### Expected behavior

The Zammad SAML SDP implementation allows enabling and configuration to sign or encrypt requests.

### Use Cases

As an administrator using Keycloak as a SAML SSO provider in the company network securing all SAML communication by signing and encrypting any SAML requests. To fit Zammad within this, the SDP has to support signing and encrypting.

---

```[tasklist]
### Tasks
- [x] Adjust Keycloak docker container to support signing/encrypting of SAML messages (base image changes)
- [x] Adjust CI
- [x] Look into SAML specification
- [x] Adjust SAML configuration screen in Zammad (admin interface; upload key + cert)
- [x] Check `omniauth` gem + make adjustments in Zammad
- [x] Validate certificate and private key
- [x] Add SSL verification check switch and info
- [x] Create documentation task
- [x] Test
- [x] Review
```

**Comment by davidtrevor23** [comment]
This also affects logout, right? ADFS requires SAML Logout Requests to be signed and throws an error message / does not respond with a SAML Logout Response if it is not signed. I see no way to define/upload a signing certificate in Zammad?

**Comment by tschaefer** [comment]
@davidtrevor23 This affects all the communication between SP (Zammad) and IDP.
