### ISSUE TITLE
Default Agent Notification Settings

### ISSUE THREAD

**Issue by dominikklein** [zammad/zammad#4591]
## Actual behavior

Currently, the default Agent notification is only adjustable via `config/application.rb` (`config.preferences_default_by_permission`) which are overwritten on any update.

In Consulting and/or Migrations Workshop, this setting must be changed in many cases or the Zammad Consultant must perform a mass update via a `rails c` command.

In the hosted environment, the only solution at present is to carry this out via the "Switch to user" function. With a correspondingly large number of agents, however, this is a tedious task.

## Expected behavior

**As an admin**
...I can set the default agent notification settings for new agents (e. g. synced via LDAP or created via Zammad).
...I can enforce/update all current agent notification settings once to default (usually done before going live or after re-organizing our basic configuration).

**As an agent/admin**
...I can reset my personal notification settings to the system default in my profile.

## Possible Solution

To make working with Zammad more effective and to improve the UX in a fresh Zammad setup or a migration to Zammad, it would be a nice feature:

a) To make the default agent notification setting available via the Admin Interface.
b) Perform a mass change/update for all agent's notification settings via the Admin Interface.

### Admin Interface - Default Agent Notification Settings

- Should the override always be for all agents or is it also possible to say, that only the agents which have currently the default settings in place will receive the new default settings? -> Only for all agents.

### Config/Settings

a) `config/application.rb` (`config.preferences_default_by_permission`) should still point to the system default (if in UI setting is reset to factory default, this should be de factory default).

b) A new Setting e. g. `user_preferences_default_by_permission`  should reflect the new default value which is saved by the Zammad admin via UI.

## Mockup

<img width="1432" alt="Screenshot 2023-01-25 at 15 50 26" src="https://user-images.githubusercontent.com/22768032/215978286-03494d1f-c4bd-41bd-9b40-5ff09600d4f3.png">

Warning before global reset (direction example):
<img width="749" alt="216006605-c9c2b272-f143-430f-87d8-8ac2bb06dd93" src="https://user-images.githubusercontent.com/5445094/234037769-7250ed00-e34e-44e9-812d-9365ed612560.png">

```[tasklist]
### Tasks
- [x] Add new setting for notification configuration (which targets `config.preferences_default_by_permission` by default). - DK
- [x] Add UI for the notification matrix setting. - DK
- [x] Add the possibility to reset to reset the personal notification settings in the profile - MM
- [x] Add the possibility to reset the new setting to the zammad system default notification setting - DK
- [x] Add the possibility to apply the current default notification setting to all users (with a warning popup) - MM
- [x] Remove usage of "preferences_default_by_permission" in user model - DK
- [x] Confirm dialog for setting apply for agents should be improved - MM
- [x] Failing setting preferences default in some situations - MM
- [x] Review
```

**Comment by Bozo0511** [comment]
I set up the Notification via admin > Settings > Tickets > Notifications 
- I applied the settings to all agents
- I reverted the setting to default

The feature works as intended.
