### ISSUE TITLE
Two-factor authentication (2FA): Authenticator App

### ISSUE THREAD

**Issue by fliebe92** [zammad/zammad#4595]
# Two-factor authentication (2FA)

Zammad is currently lacking a 2FA implementation.

## 2FA methods

There are different methods available to use 2FA and to provide a secure login.

### Authenticator app (TOTP)

We are providing the possibility to use an authenticator app on mobile phones (e.g. Google Authenticator or Authy).

For this, a QR code is generated on the user's profile page. After scanning this QR code, the authenticator app provides a one-time password (OTP) to finally enable 2FA for the user's account.

### Recovery Codes

In the first step, there is no support for recovery codes planned, however, some screenshots refer to them.

### Trusted Devices

In the first step, there is no support for trusted devices, however, some screenshots refer to them.

### Profile - Two-Factor Configuration

On the user's profile page, there is a new section called "Two-factor authentication". After navigating to this section, a user can manage their 2FA method configuration: set up new one, remove configured ones, choose their default method, etc.

![Screen Shot 2023-05-16 at 09 29 51](https://github.com/zammad/zammad/assets/6049445/5c2df4a5-2b2a-4d7a-8163-223ef56f342c)

When a user clicks on **Set Up** button in the overflow menu of a method, a modal will appear to guide them through the setup guide of the selected method. It is required to enter the current password as the first step for all 2FA methods.

![Image](https://github.com/zammad/zammad/assets/6049445/41aaea54-48aa-4df0-8efc-2c5543f3e28c)

![Image](https://github.com/zammad/zammad/assets/6049445/951e0970-a634-4cca-bef3-18ca8fecb1db)

It is possible to set up more than one 2FA method. This allows a user to switch to another correctly set up 2FA method if e.g. the mobile phone is lost. If more than one 2FA method is used, the user can choose their primary method (default). Normally, it would be the first one they set up.

### Login

After a user entered the correct credentials for their own account, we need to check if 2FA is enabled for this user record.
If 2FA is enabled and set up correctly, the user needs to provide a token. The login is only possible if a correct token was entered.

If a 2FA setup is required (chosen by an admin) and a user has not set up 2FA yet, the logged-in user needs to configure a 2FA method directly after the login. There is no chance to skip this.

#### Authenticator app (TOTP)

After the log in a "security code" field will be displayed.

<img width="566" alt="Screenshot 2023-01-18 at 14 47 29" src="https://user-images.githubusercontent.com/6049445/213206244-5fcc5a0e-615c-45fd-83a0-a8386a0bb934.png"> <img width="566" alt="Screenshot 2023-01-18 at 14 47 37" src="https://user-images.githubusercontent.com/6049445/213206256-87cab568-e569-4e2b-b905-f7ebe7200c01.png">

#### Configure Two-factor authentication

In the admin interface, there is a new tab "Two-factor authentication" below the "Security" section.

In this new tab, an admin can enforce the usage of 2FA for specific roles, e.g. all agents or all customers.

The login is working as usual, but users have to set up at least one 2FA method for their account.

In addition to this, available 2FA methods can be enabled/disabled.

<img alt="Screenshot 2023-01-19 at 16 13 06" src="https://user-images.githubusercontent.com/6049445/213494366-d977a464-e70f-4006-b0cd-f06552859f09.png">

<img alt="Screenshot 2023-01-19 at 16 13 14" src="https://user-images.githubusercontent.com/6049445/213494420-8508dda1-0be5-4b47-92b0-8a6b943cabc2.png">

#### User Management Screen

The user management screen lists the available users in the system.
A new action named `Configure 2FA` is implemented in this screen to open a dialog to do the following operations:

- Remove a configured 2FA method
- Remove all configured 2FA methods

<img alt="Screenshot 2023-01-20 at 11 58 41" src="https://user-images.githubusercontent.com/6049445/213692208-a8bdc66a-3640-4b7b-9dff-3e0bf1d75272.png">

<img alt="Screenshot 2023-01-20 at 12 11 08" src="https://user-images.githubusercontent.com/6049445/213692216-f8692afd-7660-47ff-9b8c-8d75ce7968e7.png">

## Mobile View

<img width="49%" alt="Screen Shot 2023-01-20 at 12 18 41" src="https://user-images.githubusercontent.com/6049445/213700062-f42e4783-7feb-496e-ba7d-ad8045464a47.png"> <img width="49%" alt="Screen Shot 2023-01-20 at 12 53 06" src="https://user-images.githubusercontent.com/6049445/213699678-70d6896f-b314-4c4a-822c-564ae1abf94b.png">

# User Stories

**As a user (e.g. customer, admin, agent)**
...I can use my Google Authenticator app on my company phone to provide tokens for secure login.
...I can set up (multiple) 2FA in my profile or when required also during the login.
...I can change my primary 2FA method when I have multiple available.
...I can delete a single 2FA in my profile (when it's required, one needs to be present).

**As an admin**
...I can remove configured 2FA method from other users.
...I can disable/enable 2FA and also the single 2FA method methods.
...I can enforce the usage of 2FA for the different roles.

# Idea for technical implementation<a id='idea-for-technical-implementation'></a>

With a new layer for 2FA, it should be pretty easy to provide more 2FA methods (e.g. email, security keys, ...) in the future.

## Backend

We are going to create `lib/auth/2fa.rb` that provides general functionality for all 2FA methods:

- List methods to get all available and all enabled 2FA methods in general
- 2FA setup required for a specific user
- 2FA enabled/properly configured for a specific user
- List enabled 2FA methods for a specific user
- Default configured TwoFactor-Method from a user
- Check entered token for validity for a specific 2FA method + user

### 2FA method

For all 2FA methods, there exists a base. This base provides the following functionality:

- A method `config` is provided that maps the subkeys of the `2fa_XXX` settings for easier usage:
  - `display_name`, ...
  - This is to avoid fetching the user's preferences and accessing the needed information in a cumbersome way.
- A `delete_setup` method is provided that uses the given 2FA method name to delete the current configuration for a specific user.

A 2FA method should consist of the following parts:

- The following attributes need to be defined in a new setting named `2fa_XXX` (in `preferences`):
  - Display Name
  - Description
  - Icon
  - ...
- Via a new file in `lib/auth/2fa/methods/`
  - A `setup` method is required to define the to-be-stored attributes in the user's preferences.
  - An `auth` method needs to be defined to actually perform checking if an entered token is valid or not.
  - We need a `configured_for_user?(user)` method to know if this method was properly set up for the given user.
  - It is possible to specify additional checks if this method can be enabled/used by an administrator.
  - All other specific attributes/methods are located in this file.

### `AfterAuth`

A new layer to add the possibility to hook after the authentication (=user is logged in) or a valid session check. With this, it should be possible to require the 2FA setup (it should not be possible to work with the system without doing this first).

### Open Points

- We would like to store the properly configured/set up 2FA methods for a user in the user's preferences.
  - Currently, the preferences are indexed in ElasticSearch as well.
  - TBC: Skip preferences for ElasticSearch or skip specific keys in preferences?
- How to deal with the authentication flow?
  - First, a password-only check and afterward a password check + 2FA method.
  - Password-Check and afterward only token check (and some way identifying the user?)

## Frontend (Desktop View)

It should be easily possible to add new 2FA methods inside the front end. Maybe 2FA method class that adds also some configuration (so that this can be checked/used in needed places).
For every 2FA method we need a setup output/handling and also the possibility to define a "security code" input element (there should be a default, but it should be possible to use a different one).

The setup output should be so generic that we can use it after the login but also inside the setup from the personal account profile page.

...

## Frontend (Mobile View)

For the Mobile View, we need to implement a layer that takes care of handling 2FA during the login.

To get an idea of how this could be solved, please have a look at the existing layer for the search plugins (`app/frontend/apps/mobile/pages/search/plugins/`).

This layer provides:
- an object that is used for defining all relevant frontend data
  - `setupComponentName`, optional changing the SecurityCode component, (error) messages, ...
- a composable for easy usage of 2FA 

Besides the layer, we need:
- A component for entering a security code (which is using a new field type?)
- adding 2FA login flow
  - show the default two-factor method
  - possible selection of other configured 2FA methods
- For the mobile view the setup component for the mobile view should only be some hint and a link to the desktop view.

...

---

```[tasklist]
### Tasks
- [ ] https://github.com/zammad/coordination-scrum/issues/40
- [ ] https://github.com/zammad/coordination-scrum/issues/41
- [ ] https://github.com/zammad/coordination-scrum/issues/42
- [ ] https://github.com/zammad/coordination-scrum/issues/43
- [ ] https://github.com/zammad/coordination-scrum/issues/44
- [ ] https://github.com/zammad/coordination-scrum/issues/45
- [ ] https://github.com/zammad/coordination-scrum/issues/46
- [ ] https://github.com/zammad/coordination-scrum/issues/47
```

**Comment by MrGeneration** [comment]
Isn't that a duplicate of #965 ?

**Comment by dominikklein** [comment]
I think it's not an duplicate because this issue is about a connection to an external two-factor provider. We should maybe close this linked issue when we do not want to handle this topic in the future.

**Comment by MrGeneration** [comment]
Ummm...
https://github.com/zammad/zammad/issues/965#issuecomment-1012145045

**Comment by HappyMan4** [comment]
Thanks for implementing, this is really important. 👍
