### ISSUE TITLE
Two-factor authentication (2FA): Email

### ISSUE THREAD

**Issue by fliebe92** [zammad/zammad#4615]
# Two-factor authentication (2FA): Email

Zammad is currently lacking the email method for 2FA.

## E-Mail

One option how to use 2FA in Zammad is by sending out e-mails that contain a token.

~~By setting up this method as well as by logging in, an e-mail is sent out to the e-mail address which is stored in the user record. The mail contains a one-time password (OTP) which is valid for X minutes. Due to slow mail servers, the token lifetime needs to be configurable.~~
Another approach would be to use the existing Zammad "Token" mechanism which will generate a not persistent token based on the user and an expire-Date. The token will be invalid after it was used.

This method is only available if Zammad is correctly configured to send out e-mails. And for the user, it's only possible to use this method when the user has a filled email address field.

It should be possible to re-send the token (with a limit/abuse check).

### Profile - Two-Factor Configuration

The new method should also be visible inside the "Password & Authentication" area in the personal profile settings.

![two-factor-email-personal-profile](https://github.com/zammad/zammad/assets/5445094/68cde330-7a23-4d0d-81e1-f0925e333e3c)

When a user clicks on **Set Up** button in the overflow menu of a method, a modal will appear to guide them through the setup guide of the selected method. It is required to enter the current password as the first step for all 2FA methods.

The initialization of the setup should send an email that has the first verification token which needs to be entered in the configuration screen.
It should be possible to resend the verification email.

SCREENSHOT NEEDED

### Login

After a user entered the correct credentials for their own account, we need to check if 2FA is enabled for this user record.
If 2FA is enabled and set up correctly, the user needs to provide a token. The login is only possible if a correct token was entered.

#### E-Mail 

After the log in a "security code" field will be displayed (and in the background, an email is sent). It should be possible to resend the verification email.

SCREENSHOT NEEDED

#### Configure Two-factor authentication

The new 2FA method can be enabled/disabled.

## Mobile View

The new method should also be usable in the mobile view. It's very similar to the authenticator app method. A security code field should be visible where the code from the Email should be entered. It should be possible to resend the verification email.

SCREENSHOT NEEDED

### Clarification

- Can we add secure emails (as an optional thing)?

```[tasklist]
### Tasks
- [ ] Two-factor method in the backend layer (module + setting) - (Sending email configured? / User has email filled?)
- [ ] Two-factor setup modal in the desktop view
- [ ] Two-factor login handling in desktop view
- [ ] Mobile-View: Two-factor login handling
```
