### ISSUE TITLE
Two-factor authentication (2FA): Security Keys

### ISSUE THREAD

**Issue by fliebe92** [zammad/zammad#4616]
# Two-factor authentication (2FA): Security Keys

Zammad is currently lacking the security keys method for 2FA.

## Security Keys (WebAuthn)

Zammad can use WebAuthn to interact with software and hardware security modules.

- Modern browsers already support WebAuthn
- Both software and hardware authenticators are usable (e.g. fingerprint + USB security keys)
- Authenticator needs to be registered once
  - Very easy to setup
  - Usable in a few minutes
- Multiple authenticators can be registered + used
- Authenticators can be removed (e.g. USB security key is broken/lost)
- Each login needs to be confirmed with the selected authenticator

Some technical background:

- https://webauthn.io/
- Ruby gem: https://github.com/cedarcode/webauthn-ruby

### Profile - Two-Factor Configuration

The new method should also be visible inside the "Password & Authentication" area in the personal profile settings.

![Password   Authentication_ No Setup](https://github.com/zammad/zammad/assets/6049445/2873f4f5-479d-4a0c-905d-afd902e0ef35)

When a user clicks on **Set Up** button in the overflow menu of a method, a modal will appear to guide them through the setup guide of the selected method. It is required to enter the current password as the first step for all 2FA methods.

![Set up_ Password](https://github.com/zammad/zammad/assets/6049445/77b8e541-fd61-46af-b43c-2532c2870f01)

![Set up_ No Keys](https://github.com/zammad/zammad/assets/6049445/9c8f8136-fc09-4b60-bed6-493998b6f4bf)

![Set up_ Key Name](https://github.com/zammad/zammad/assets/6049445/28ddd38c-d9b9-4de6-a950-4b9d324d5a20)

![Set up_ Browser Interaction](https://github.com/zammad/zammad/assets/6049445/5b24ea2f-2bfa-4e2e-8c47-b1d4526f9e9a)

Already configured keys can only be removed. A customized key name and creation time allow for easier identification.

![Set up_ One Key](https://github.com/zammad/zammad/assets/6049445/9982cedd-e145-41d6-9675-e1868d5e219e)

In case of set-up errors, a suitable error message is shown to the user, allowing them to retry the process.

![Set up_ Error Control](https://github.com/zammad/zammad/assets/6049445/4bdb9f87-7836-4d64-a6c8-08cb6788e6bc)

It should be possible to edit the Security Keys configuration to add additional Security Keys (this is different from most other methods). The edit action actually opens the same dialog as Set up action.

![Password   Authentication_ With Security Key Set Up](https://github.com/zammad/zammad/assets/6049445/23b436f3-c49e-4fa6-8ecc-fbfcd7dc532e)

With multiple authentication methods set up, it is possible to set a default method. This action is available for all currently configured methods, except the current default (which gets a badge next to its name).

![Password   Authentication_ With Another Method Set Up](https://github.com/zammad/zammad/assets/6049445/1a878ef3-37ea-4815-856b-5927ab096c8b)

When possible the count of configured keys should be present as a badge (similar to the default badge).

### Login

After a user entered the correct credentials for their own account, we need to check if 2FA is enabled for this user record.

#### Security Keys (WebAuthn)

After the login, the browser will automatically ask the user to use their security key/device.

<img width="593" alt="Screenshot 2023-01-18 at 14 59 38" src="https://user-images.githubusercontent.com/6049445/213206516-251a5496-e564-481a-89b5-23173bcbcbf5.png">

In case of errors, the user will be able to recover via another 2FA method.

<img width="606" alt="Screenshot 2023-01-18 at 14 58 28" src="https://user-images.githubusercontent.com/6049445/213206739-0dedef7d-2f49-45f7-b7c5-096f2838be20.png">

#### Configure Two-factor authentication

The new 2FA method can be enabled/disabled.

## Mobile View

The new method should also be usable in the mobile view. It's different to the normal "security code" methods.

<img width="49%" alt="Screen Shot 2023-01-20 at 12 22 35" src="https://user-images.githubusercontent.com/6049445/213699824-698b2f88-0f45-423f-a543-8eab7a51383a.png"> <img width="49%" alt="Screen Shot 2023-01-20 at 12 25 05" src="https://user-images.githubusercontent.com/6049445/213699877-41c2e0d2-32d2-4f2e-8b7a-5ba467e2364d.png">

```[tasklist]
### Tasks
- [x] Two-factor method in the backend layer (module + setting) - FL
- [x] Two-factor setup modal in the desktop view - DV
- [x] Two-factor login handling (no security code means completely different handling) in desktop view - DV
- [x] Mobile-View: Two-factor login handling (no security code means completely different handling) - VS
- [x] Possibility to add multiple keys == edit functionality in personal preferences - FL/DV
- [x] Personal-Preferences: Frontend action to set preferred/default two-factor method - FL
- [x] Personal-Preferences: Endpoint for saving preferred/default two-factor method - FL
- [x] Improve try another method screen in desktop view - DV
- [x] Tests - FL/DV
- [x] Add migration for default two-factor authentication method (if it was set up before) - FL
- [x] Exclude recovery codes method from being set as default two-factor authentication method in preferences - FL
- [x] Review
```
