### ISSUE TITLE
Two-factor authentication (2FA): Recovery Codes

### ISSUE THREAD

**Issue by fliebe92** [zammad/zammad#4620]
## Actual behavior

The new 2FA implementation currently does not have support for recovery codes.

## Desired behavior

If you lose access to your two-factor authentication credentials, you can use your recovery codes to regain access to your account. Afterward, you can reset your 2FA on a new device.

### Profile - Two-Factor Configuration

In the `Password & Authentication` part of your user profile, the user will see a separate section for the recovery codes, right below the list of available two-factor authentication methods.

In case no methods have been set up, the recovery code section will not be visible.

![Password   Authentication_ No Setup](https://github.com/zammad/zammad/assets/6049445/8f2ed768-dd4d-47b6-b24f-ad969b64ef6a)

In case at least one method is set up, and recovery codes are already generated, there will be an option to regenerate them.

![Password   Authentication_ Re-generate](https://github.com/zammad/zammad/assets/6049445/28dd467d-bcd7-41da-9420-2d2469701e6d)

In case at least one method is set up, but recovery codes were not already generated (i.e. a method was set up before this feature was enabled), there will be an option to explicitly generate them.

![Password   Authentication_ Generate](https://github.com/zammad/zammad/assets/6049445/47b5c764-6092-4d5e-b362-84db66146ae9)

Upon the click on **Regenerate** or **Generate** button, the user will first have to enter their current password.

![Set up_ Password](https://github.com/zammad/zammad/assets/6049445/4d41abc9-2e9e-4111-9df8-1818f3322562)

The recovery code (re)generation is immediate, no additional input from the user is required. The user is always presented with a list of 10 recovery fresh codes.

They have an option to print them out or copy them, and finish the process by closing the modal. From then on, generated codes are nowhere visible, the only way to get them shown again is by regenerating them.

![Password   Authentication_ Set Up](https://github.com/zammad/zammad/assets/6049445/2f5ba01c-2d37-4460-8398-18324c3864ac)

The generation of recovery codes will happen automatically upon successful verification of the first two-factor authentication method for the user if the recovery code method is enabled. During the setup guide, as a last step, the user will immediately receive the list of 10 recovery codes.

### Login

During the sign-in process, in the 2FA screen, the user has the possibility to click on **Try another method** in case they have at least one other method or recovery code set up.

![Login_ Authenticator App](https://github.com/zammad/zammad/assets/6049445/00c03c80-e467-43eb-88d4-1cd8574b3337)

In the **Try another method** screen, the list of buttons will show all setup methods for the user, and, in case they have generated them, the additional link for the usage of recovery codes is below.

![Login_ Try Another Method](https://github.com/zammad/zammad/assets/6049445/a084f22d-f460-41d2-9fa6-a830c3c0404b)

Finally, in the recovery code screen, the user is asked for one of their recovery codes, which was not used before.

![Login_ Recovery Code](https://github.com/zammad/zammad/assets/6049445/b3ba9b43-328b-445a-bc61-528271f7cf07)

### User Management Screen

An admin is not able to delete/recreate the recovery codes for a specific user. 

### Technical Implementation

Recovery codes for a user get automatically deleted if the last 2FA method that was configured got deleted.

```[tasklist]
### Tasks
- [x] Two-factor recovery code handling beside the "real" methods (+setting) - DK
- [x] Two-factor recovery code handling during the setup in the frontend (when it's activated) - MM
- [x] Endpoint for two-factor recovery code creation - DK
- [x] Two-factor recovery code login handling in desktop view (addition inside the try another method) - MM
- [x] Mobile-View: Two-factor login handling (addition inside the try another method) - VS
- [x] Review
```

**Comment by fliebe92** [comment]
https://git.zammad.com/zammad/zammad/-/merge_requests/5874
