### ISSUE TITLE
Enhance time-tracking to specify display unit

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#4637]
### Usecase:
- As a new agent I don't know what time unit to deposit in my tickets. so I would always have to ask an admin what is wanted here. Therefore a display when entering the accounted time would be helpful.

- As an admin, I may change the accounted time unit due to a new accounting system I have connected to Zammad. For this I would need to send information about this to each agent. By having a menu where I can define which unit of time is currently being used, this would eliminate the need for this and prevent errors.

### Expected behavior:

- As an admin, I am able to specify which time unit agents should enter.
- As an agent, I see what unit to use when entering something into time-tracking.
- (check if its possible to make the custom time unit translatable)

### Actual behavior:

- Admins need to make sure, it's common knowledge among the agents what time unit to use.

### Implementation details:

- Dropdown field (min, quarters, hrs) plus "custom-field" to type your own unit in an input field
- Add a hint for admins: "This is a display unit. that the admin knows, that in case he changes the unit from (for example) hours to minutes, it won't change any value, only the display."

#### Manage Time Accounting Screen (admin)

![Manage Time Accounting](https://github.com/zammad/coordination-private-features/assets/6049445/83e63527-2978-4098-83cb-4c321ac3f4ac)

![Unit Options](https://github.com/zammad/coordination-private-features/assets/6049445/b2ab254d-f652-462d-8148-ec5bbc41cbab)

![Custom Unit](https://github.com/zammad/coordination-private-features/assets/6049445/1dcdfd6c-fb43-4453-a997-bf4535184932)

#### Ticket Zoom Screen (agent)

![Ticket Zoom](https://github.com/zammad/coordination-private-features/assets/6049445/986e0d3d-5d8b-44d6-b1b5-7131101f5b81)

```[tasklist]
### Tasks
- [x] Display Unit setting inside admin area (dropdown + custom possibility) -> Clarify static values (DV)
- [x] Output display unit inside time accounting ticket dialog (DV)
- [x] Check if translation would be possible with current approach (DV)
- [x] Output display unit in ticket zoom (desktop view) and detail view (mobile view) (DV)
- [x] Tests (DV)
- [x] Review
```

**Comment by KoJie** [comment]
Additional notes:

### expected behaviour:

- As an admin, I would like to be able to translate this unit as well, so that each agent can see it in their language

**Comment by KoJie** [comment]
Refinement-Meeting 31.05.2023:

- dropdown field (min, quarters, hrs) plus "custom-field" to type your own unit in an input field
- add a hint for admins: this is a display unit. that the admin knows, that in case he changes the unit from (for example) hours to minutes, it wont change any value, only the display
- no changes in the export needed
- the unit needs to be translatable

**Comment by dominikklein** [comment]
@dvuckovic Do you have time to add two mockups until the end of the week? One for the admin interface and one for the agent dialog.

Otherwise, I can also try it tomorrow :-)

**Comment by dvuckovic** [comment]
OP comment was updated with mockups.

**Comment by dvuckovic** [comment]
@KoJie Can we confirm the available options for time accounting units? Currently we have the following:

- no unit
- hour
- quarter-hour
- minute
- custom

Are we missing something from the list?

**Comment by KoJie** [comment]
yes, lets take this set. I know that some people also use "days/ person days". But that's probably pretty rare, so let's take this as the first version and see if there's feedback.
