### ISSUE TITLE
New conditions for input fields: "starts with", "ends with", "is" and "is not"

### ISSUE THREAD

**Issue by dominikklein** [zammad/zammad#4661]
### Summary (What)
As an administrator, I want to solve the problem that tickets can be assigned/filtered depending on the first/last characters from the field content (or equal/not equal to specific content).

For example, it should be possible to use the first letter of the customer's name to decide which agent should work on a ticket or trigger some other action related to the ticket.

**Example Use Cases** 

_Overviews:_
Team A works on tickets the customer's last name starts with A OR B OR C OR D OR SCH,
Team B works on tickets the customer's last name starts with E OR F OR G OR H OR I OR J

_Postmaster Filter / Ticket-Auto Assigment:_
Agent Dummy Dumson is responsible for all customers of a certain region. So every incoming mail from customers, whose postal code starts with 58, he will be assigned automatically.

_Triggers:_
I want triggers to send emails based on the customer's postal code or last name. "Dear customer, your assigned contact person will be ______."

_Schedulers:_
I have a new object to define as an attendant to a customer or organization. All organizations starting with letters A, B, C, U, X, etc. or all organizations in postal code areas 5-6 are my responsibility.

_Report Profiles:_
I want to see, how many customers I have in certain regions.

### Intended Outcome

As an administrator, I can define specific use cases for assigning/filtering tickets under the conditions inside the different admin areas (overviews, postmaster filter, trigger, scheduler, ticket auto-assignment, and report profiles).

### How will it work

There are new conditions available for input fields:
* `starts with`
* `ends with`
* `is`
* `is not`

To be clarified:
_It should be possible to add multiple values per condition instead of having always another row (similar to the tags field)._

### Technical Implementation Thoughts

- By supporting multiple values for new operators, we would end up with inconsistencies with other operators, namely contains for input fields, since it supports only a single value at the moment.
- One idea would be to improve all applicable existing operators as well, but in a "smart" way. The back-end would continue to support both single + multiple values for these operators, but do an in-place migration whenever the condition is edited (this can be done exclusively in frontend).
```[tasklist]
### Tasks
- [x] Add new operators to input fields (in ticket context) - FL
- [x] Add new operators to input fields (postmaster filters) - FL
- [x] Add tag like behavior for new operators - FL
- [x] Add new operators in the backend (in ticket context) - FL/MG
- [x] Add new operators in the backend (for postmaster filters) - FL/MG
- [x] Make sure existing triggers that use input fields are still working fine
- [x] Tests
- [x] Review
```

**Comment by mgruner** [comment]
## Discussion 2023-06-28

There are serious issues with supporting multiple values for the new operators and for `contains` / `contains not`.

- Zammad uses [bootstrap-tokenfield](https://github.com/sliptree/bootstrap-tokenfield), which is EOL. It forces to use a delimiter character, which is the comma.
  - This means: when entering values to filter for, the comma will not be usable
  - Existing values for `contains` / `contains not` will break after the migration, because they get split up at the comma.
- The UI is not fully intuitive. If multiple values are OR connected, it will not work properly for negated filters (`is not 'a' OR is not 'b'` always is true).

### Decision

The multiple value part will be taken out of this feature at this point and discussed in a refinement for a follow-up task.

**Comment by mgruner** [comment]
## Discussion 2023-06-30

- The tags field is also broken (no commas allowed)
- For the `contains`, `contains not`, `is` and `is not` fields the current limitation is acceptable, but not for `starts_with` and `ends_with` (LHM requirement)

### Option 1
- Fix the bootstrap token-field so that all regular characters can be used and data saves cleanly as array in the database, or exchange it for another library to be used
- Rename `starts_with` to `starts with one of` and `ends with` accordingly, and turn them to supporting multiple values
- Fix the tags field to use corrected behaviour and migrate stored data to arrays as well

### Option 2
- leave `starts/ends with` and the token field as they are
- add a new operator `matches regular expression`, but only for triggers
  - this would allow powerful queries, including ranges which would fit much better to the use case of selecting character ranges
  - Regex is heavy on performance, but this should be ok with triggers as they only look at one ticket in the database. We should not allow this for overviews and schedulers.
  - We can probably only add this for PostgreSQL as MySQL regexes are very different, but that should be ok since it is deprecated.

Hint: another task should also be created to migrate the ugly `contains: "regegex:my_string"` of the postmaster filters to a real operator like described for Triggers above.

**Comment by mgruner** [comment]
@YetAnotherGerrit said he would prefer option 2.

**Comment by mgruner** [comment]
@KoJie please have a look at the recent updates.

**Comment by martini** [comment]
Just as additional information. 

a) Token Fields: bootstrap addon "token-field" has also issues if it's rendered on hidden DOM elements (e. g. hidden tasks). So here IMO we need a replacement anyway.

b) Maybe other UI element: For tickets zoom, we use already another tag widget, maybe we can use it also here?
<img width="271" alt="Screenshot 2023-07-01 at 03 24 00" src="https://github.com/zammad/zammad/assets/110226/7851bf5d-4229-4d2d-abb8-d66a2805939c">

c) Options: I like the approach to make the feature use friendly, for this I would like option 1 (for overview,trigger,scheduler,core workflows, and so on) and in addition if possible option 2 (for triggers only).

d) Performance: As already mention above, option 2 - regex support can only get used in triggers (no other ticket selectors). For performance reasons.

e) Consistency: For consistency reasons we should think about to align all conditions in post filter too (it is similar to the hint above - I just want to point it out)

**Comment by martini** [comment]
And a general technical question: Since we increase (specially in case with `ends with` - because no index can get used there) the load to the database, did somebody do performance tests already?

**Comment by dominikklein** [comment]
But did we not explicitly decide against the regex, why is it a topic again and needed? 
@martini But it could be a performance problem in all places (also in triggers) or?

For me, it sounds like the best solution to customize the token field for our needs.

**Comment by mgruner** [comment]
> But did we not explicitly decide against the regex, why is it a topic again and needed? 

It's not needed. It's just one possible solution for the issues described. And actually it fits the use case of the customer better because you can specify ranges and negate stuff.

> @martini But it could be a performance problem in all places (also in triggers) or?

For triggers it should be fine because they only look at one ticket in the database. For regular queries I would also not recommend it. That means if overviews are required for this workflow, regexes cannot be the solution there.

**Comment by mgruner** [comment]
## Discussion 2023-07-04

- We want to implement regex support for Triggers only (possibly only for Postgres, but that can be checked)
  - We probably also need a negated operator, so `matches regular expression` and `does not match regular expression`
  - As an alternative, the expert mode with multiple conditions can already be used to achieve ranges
- We also want to improve the usage of regexes in postmaster filters by migrating them out from contains/contains not to separate operators like described for the triggers above
- To be clarified: what about overviews and schedulers? We cannot use regexes there because of performance considerations. Would a workaround be sufficient like setting a select field from a trigger that can then be used in conditions in overviews/schedulers?
