### ISSUE TITLE
Add regex as operator for ticket filter in triggers

### ISSUE THREAD

**Issue by mgruner** [zammad/zammad#4702]
As discussed in #4661, we want to add new operators `matches regex` and `does not match regex` as new operators for ticket selection in triggers. This is specifically not available for overviews and schedulers, as there would be severe performance issues with databases. It works in triggers because they only look at one ticket at a time.

An implementation of Postgresql only is sufficient; check how regex support is for MySQL.

Optional: we can see if there is an available regex validation library for the front end that could warn the administrator when they are constructing obviously broken regular expressions.
```[tasklist]
### Tasks
- [x] Add conditions to front end, but for triggers only - FL
- [x] Clarify if we should also add to ticket auto assignment
- [x] Evaluate possibility of basic front end validation
- [x] Validate conditions (including regexes) in the database before saving them
- [x] Clarify if this feature should be available for all Hosted contract levels
- [x] Add support for regexes in back end (MG)
- [x] Check for mysql support of Regexes
- [x] Rename existing operators in time accounting selector
- [x] Rename existing operators in core workflows
- [x] Tests
- [x] Review
```

**Comment by mgruner** [comment]
A simple solution for validation might be constructing `RegExp` objects in JavaScript and checking if they thow `SyntaxError`s.

```
new RegExp('(')
VM164:1 Uncaught SyntaxError: Invalid regular expression: /(/: Unterminated group
    at new RegExp (<anonymous>)
    at <anonymous>:1:1
```

**Comment by mgruner** [comment]
@martini informed that regexes should be validated in the database directly, to ensure they are valid and don't cause aborted transactions, leading to not created tickets/articles.
Something like this should already be in place: overviews are validated by executing them, before they get saved. Not sure where, we need to validate this.

**Comment by martini** [comment]
Result (from Meeting with Johanna):

a) `regex as operator` should be available on `auto assignment` too
b) a new `setting` for enable/disable the regex as operator support globally need to get introduced (because `ticket_allow_expert_conditions` can not get re-used - its misleading @fliebe92 )

**Comment by KoJie** [comment]
addition: Regex for trigger & auto assignment should be enabled for plus-customer only

**Comment by rolfschmidt** [comment]
naming should be equal to core workflow.

 `regex match`  + `regex mismatch`

**Comment by GeoffreyFrogeye** [comment]
This change is definitely an improvement, it makes things clearer.

However, there is a lack of migration path. On my company's instance some filters started to fail silently because filters with `contains` `regex:...` were not working anymore and had to be changed to `matches regex` `...`. We weren't expecting that, and it wasn't easy to debug, although it was relatively easy to fix.

I would have liked (by order of preference) an automatic migration taking care of this, or keeping the old behaviour working until the next major release with a related important announcement, or a mention of this as a breaking change on the 6.1 release notes.

I hope this criticism was constructive and helpful for you.

**Comment by MrGeneration** [comment]
Are you sure your database migrations where running successfully?
Zammad automatically is migrating those filters.

**Comment by GeoffreyFrogeye** [comment]
Indeed, it seems they weren't run correctly due to an incomplete filter:

```
...
== 20230802112821 RegexOperatorRenaming: migrating ============================
== 20230802112821 RegexOperatorRenaming: migrated (0.0301s) ===================

== 20230807051414 InputFieldsOperatorRenaming: migrating ======================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Validation failed: The required 'perform' value for x-zammad-ticket-customer_id, value is missing!
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.6/lib/active_record/validations.rb:80:in `raise_validation_error'
...
```

I got this from `apt` log. I guess the Debian package doesn't mark the installation as failed if migrations failed, hence why we didn't catch it.

Finding the incriminating filter and fixing it (adding a customer to a "set customer" action) and running `zammad run rake db:migrate` manually correctly ran missing migrations, which also correctly renamed a test `regex:` filter I left.

Thanks for the pointer, and sorry for wrongly assuming there wasn't an automatic migration for this.
