### ISSUE TITLE
Enhance regex handling in postmaster filters

### ISSUE THREAD

**Issue by mgruner** [zammad/zammad#4703]
Currently, postmaster filters support the operators `contains` and `contains not`. By placing a value prefix `regex:`, it is possible to specify regular expressions to match against the fields.

We want to change this so that the regular expressions become regular operators like for triggers in #4702. Existing filters must be migrated. After this change `contains` and `contains not` will only perform normal string comparisons, and the new operators handle the regular expressions.

Optional: check for regex validation library like in #4702.
```[tasklist]
### Tasks
- [x] Add support for regex in backend
- [x] Repair / align `validate_condition` for the new operators, including is/is not/starts with/ends with
- [x] migrate existing filters to the new operators
- [x] remove support for `regex:` prefix from contains/contains not and clean up the code
- [x] tests
- [x] review
```
