### ISSUE TITLE
Simplify the definition of multiple values for specific condition operators

### ISSUE THREAD

**Issue by dvuckovic** [zammad/zammad#4709]
## Summary (What)

As an administrator, I want to be able to easily manage multiple values in conditions for specific operators like `is`, `is not`, `starts with` and `ends with`.

For example, match if ticket's customer last name starts with A OR B OR C OR D OR SCH.
Or, match if ticket's customer last name starts with E OR F OR G OR H OR I OR J.

It should not be needed to resort to Expert Conditions to configure this relatively simple condition with many OR clauses that match on the same attribute. This is diffuclt to maintain and seems like an overkill for the example use case.

## Intended Outcome

As an administrator, I can specify multiple values for an operator by using a tokenized field that will allow input of many different inline values, presenting them in a readable and concise way.

The new tokenized field will behave in a very similar way to the existing tags field, with some notable differences:

* There should be no hard defined delimiter like a comma (,); tokens can be explicitly defined via `Tab` key or by removing the focus from the input field.
* There will be no autocomplete dropdown shown when entering new values.

<img width="966" alt="Screenshot 2023-07-06 at 15 52 39" src="https://github.com/zammad/zammad/assets/6049445/ad08689b-02ab-42b0-934e-9c410ecd0644">

## Technical Implementation

Provide a new field based on the same `bootstrap-tokenfield` library like the tags field.

Currently, `bootstrap-tokenfield` plugin requires a delimiter which is hardcoded to a comma (`,`). It's not possible to set it to an empty string (`''`), since it will store the value as a simple string, and on next reload it will result in a single token.

Instead, consider switching to building and storing of the value as an array of strings, serializing and deserializing it in the client so it can maintain the list of tokens.

Existing conditions should be manually migrated to the new value structure, whenever the surrounding entity is updated (i.e. Trigger).

Rename `starts with` to `starts with one of` and `ends with` to `ends with one of` operators accordingly.

## Clarify

* The proposed UI is not fully intuitive. When multiple values are OR connected, it will not work properly for negated filters (`is not 'A' OR is not 'B'` will always be true). Question: should we avoid multiple values for `is` and `is not` and stick to `starts with` and `ends with` only?
```[tasklist]
### Tasks
- [x] Build new field `tokenfield` (DV)
- [x] Make sure that values are stored as array of string + serializing/deserializing is working fine (DV)
- [x] Migrate existing conditions with 'old' operators in place (frontend) (DV)
- [x] Rename `starts with` to `starts with one of` (FL)
- [x] Rename `ends with` to `ends with one of` (FL)
- [x] Rename `is` to `is any of` (FL)
- [x] Rename `is not` to `is none of` (FL)
- [x] Support 'old' + new operators in the backend (FL)
- [x] Adjust frontend code for postmaster filters, core workflows, ... (DV)
- [x] Tests
- [x] Review
```

**Comment by mgruner** [comment]
One possibility might be to rename them to `is any of` and `is none of`, or similar. That should be unambiguous.

**Comment by KoJie** [comment]
> One possibility might be to rename them to `is any of` and `is none of`, or similar. That should be unambiguous.

I like this idea. Thus, we do not exclude the cases and it is clearly described in my eyes.
