### ISSUE TITLE
Add STARTTLS support for LDAP connections

### ISSUE THREAD

**Issue by dominikklein** [zammad/zammad#4746]
### Summary (What)

The LDAP integration currently does not support STARTTLS as an encryption method and thus is unsupported by many common LDAP setups as LDAPS is deprecated as of [2003 per RFC3494](https://www.rfc-editor.org/rfc/rfc3494), with STARTTLS being built into the LDAPv3 standard.
Currently, we have a situation where it's only possible to use the already deprecated LDAPS.

### Use cases for the feature idea.

LDAP setup doesn't allow to use an LDAPS connection, so I need to use the preferred/modern STARTTLS encryption method for the LDAP connection.

### Intended Outcome

It should be possible to still use no SSL, SSL, or STARTTLS in the LDAP configuration.

### Technical information

Switch the current "SSL" field (no/yes) to an "Encryption/Security" field with the following options: no, SSL, and STARTTLS).
With this change, the "Protocol" (ldaps:// or ldap://) can be removed from the host value because it's no longer needed to detect the encryption.

<img width="815" alt="image" src="https://github.com/zammad/zammad/assets/8327427/08f00ec7-d78b-4d40-a6ce-ffc2bc77643b">

<img width="803" alt="image" src="https://github.com/zammad/zammad/assets/8327427/70cb0062-4839-4dd0-b5ae-6161df4cc086">

For the existing installations, migration needs to be added, which moves the current "no/yes" value to the new options. And also removes the no longer needed protocol inside the host value.

PR-Reference: https://github.com/zammad/zammad/pull/4440
```[tasklist]
### Tasks
- [x] Migration for current value to new values and remove
- [x] Change field in LDAP wizard
- [x] Check saving of new value in backend
- [x] Add usage of new value in backend and implement STARTTLS
- [x] Add test cases for starttls
```

**Comment by mgruner** [comment]
`Encryption` is perhaps not the best name. How about `Transport security`? Alternatively, we could stay with `SSL`, and have `do not use SSL`, `SSL`, and `STARTTLS`. 🤷

**Comment by dominikklein** [comment]
For now, we added the same dropdown as we already have in the E-Mail configuration (we will update the screenshots).
