### ISSUE TITLE
Show as an addition also accounted time by types in ticket detail

### ISSUE THREAD

**Issue by fliebe92** [zammad/zammad#4759]
### Actual behavior
In the new [Time Accounting Type- Feature](https://github.com/zammad/zammad/issues/4533) you will have the types only visible while adding them. As an agent I don't have an overview of the different types of accounted time in total in a ticket.

### Expected behavior
In the ticket I want to be able to see how much of the total processing time is divided between the different types. That should appear here at the section:

![Image](https://github.com/zammad/coordination-private-features/assets/22768032/204d7db8-169b-4460-a2bc-aeafc3e3ef7d)

However, the information displayed should not be too much at the point. With two stored types, the display is still clear. However, if there is the use case that 5 or more types are stored per ticket, it will quickly become overloaded. 

### Usecases
- As an agent I want to jump into a ticket and easily see what accounted types are used the most here
- as an agent I want to have the opportunity to see all accounted times and types - but i don't need (and want) to see that straight away. A click to another window (or anything else) will be sufficient and will remain the ticket-view more clean.
- as a customer & admin I don't have any contact with this feature

### Technical Implementation

* We are showing the total sum of the accounted time as of now.
  * In addition to this, we are showing the accounted time grouped by time accounting types in a table underneath the total in the desktop app and the mobile view.
    * By default, we are showing the top 3 time accounting types and a row labeled with `others`.
```[tasklist]
### Tasks
- [x] Fetch needed time accounting data for desktop view
- [x] Display table in desktop view
- [x] Fetch needed time accounting data for mobile view
- [x] Display grid in mobile view
- [x] Tests
- [x] Review
```
