### ISSUE TITLE
Add new Object Manager Attribute: External Data Source (JSON)

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#4766]
### Summary (What)
It's often essential to reference data from external sources in Zammad tickets. Instead of directly importing/copying this data into Zammad (=preventing the data from being maintained in two places), users should have the capability to select a related entity from these sources. Once selected, the ticket detail view would present the entity's name, along with a link for deeper insight. For example, consider an external product database: if a ticket pertains to a specific product, users can select it. The product name then appears in the ticket, and an accompanying link directs users to the external database for a detailed product view.

### Use cases

**1) ISP:**
Incoming tickets must be assigned to a server by an agent.

The server involved is stored in an additional ticket attribute. 

The possible servers are more than 20,000 and are maintained in an external data source.

**2) Online shop:**
Complaint tickets to be created (or complaint tickets already created) must be linked to a purchase order.

The orders are maintained in an external system and are more than 1,000 pieces per day.

**3) Service provider:**
For billing purposes, a project must be attached to a ticket. The project is identified via an additional ticket attribute.

Projects are added more and more (over the years 4000). An auto-completion would be very helpful.

**4) System database:**
For support requests related to a hosted SaaS product, it's essential to select the relevant system from a database during ticket classification.
(The system database is dynamic, and it should not be necessary to synchronize it with Zammad when something changes inside the system database.)

**5) Contract:**
The company holds the contracts with the customers inside an external ERP system. During the creation of the organization inside Zammad, it needs to be possible to select the contract for this organization from this external source.

_General:_

I have a list of values (e.g. 10,000 cities) and I would like to assign them to a ticket via object manager attributes. I can't use select fields and keep them there because they will not be rendered properly. So I need a scalable solution for this which works also for 100k rows.

**As an admin...**

- I want to search in a big list (e.g 100k values)
- I want the possibility to create, remove, and update the values over time when needed.
- I don't want to sync values on different places (Zammad & an external database)

**As an agent...**

- I want to select one of the 100k values and assign it to the ticket in the ticket zoom.

Basically a key value lookup.

### Intended Outcome

It's essential to have a custom field (a new object attribute field type) that can search within specified external data sources. During form input, users should be able to select an entity from these sources. The ticket detail view should then display the chosen entity's display value, and optionally, a link to the external data.

#### Optional ideas - done

- "Sandbox" inside the object attribute configuration 

#### Postponed/Optional ideas 

- Possibility to use POST-Endpoints
- Caching search requests
- Prefill autocomplete search with a selected value from another field inside the form.

### Technical Implementation

**Attribute-Name:** External Data Source (JSON)

I would like to create a new attribute "External Data Source (JSON)" in the object manager attributes:

![image](https://github.com/zammad/zammad/assets/5445062/3b052e1d-4682-4e82-a1b6-9c23e78d188b)

Here, I can define the endpoint to which I would like to connect. In the current use case, it would be viable to add the list of cities to a dedicated index in the elastic search and keep them updated. Then I can configure the URL and the key that I would like to save in the field.
Besides the basic authentication, it should be possible to use a token-based authentication.

It should also be possible to use the link templates like in other fields (e.g. text or single select).

Needed configuration fields:
- Search-URL
- HTTP-BasicAuth
- Token-Based Authentication
- Search-Result List-Key
- Search-Result Key
- Search-Result ID-Key
- Search-Result Display-Value-Key
- SSL Verify

This field will then provide me with an AJAX-based search field in Zoom:

![zoom](https://github.com/zammad/zammad/assets/5445062/6ff2b161-c1e0-430c-abbf-90845c95fc72)

#### Value-Handling
We are saving the ID and the Display-Value during the updating of a ticket (when something was selected). It will not be updated in the future, only when you change the field value (you could search again for the same entity, and when for example the display value changed, this will count as a new value).

When the entity is deleted on the external side, it is not relevant for Zammad. Inside Zammad it will be handled similar to the historical value. It will stay inside the ticket and be visible in the detail view.

#### Core Workflow

Inside core workflow, we want to support it inside the conditions. For the actions we support only the ones that are not related to the value (e.g. show/hide, required)

#### Trigger (and others)

It could be used in the conditions. The situation for the actions needs to be checked.

#### Error Handling

For the agent, we would show only an empty result.

The failing requests should be added inside the HTTPLog.

#### Testing

One idea for a "real" integration test could be the usage of the elastic search (which is also present in the CI).

#### Technical clarification:

- [x] Should we fetch always the display value from the external source (=we would need a get endpoint for a single item) or are there other options (maybe caching the current display value and updating it in the background).
- [x] Check if we need to add the possibility about the HTTP-Method (GET or POST).
- [x] Solution for deleted entities on the external side.

##### Display Value / Search

- One idea would be to have some cache configuration in the object manager attribute configuration.

<details>
  <summary><strong>Example Data Source with Elasticsearch</strong></summary>

```
$ curl http://localhost:9200/cities/_search?q=* | jq .
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 3,
      "relation": "eq"
    },
    "max_score": 1,
    "hits": [
      {
        "_index": "cities",
        "_type": "_doc",
        "_id": "7z55AooBcmakvBEK-_Ql",
        "_score": 1,
        "_source": {
          "id": 1,
          "name": "Hamburg"
        }
      },
      {
        "_index": "cities",
        "_type": "_doc",
        "_id": "8D56AooBcmakvBEKM_Rk",
        "_score": 1,
        "_source": {
          "id": 2,
          "name": "Berlin"
        }
      },
      {
        "_index": "cities",
        "_type": "_doc",
        "_id": "8T56AooBcmakvBEKU_Rg",
        "_score": 1,
        "_source": {
          "id": 3,
          "name": "Cologne"
        }
      }
    ]
  }
}

ubuntu-rs@ubuntu-rs:/workspace/git_zammad/zammad$ curl http://localhost:9200/cities/_search?q=* | jq .hits.hits
[
  {
    "_index": "cities",
    "_type": "_doc",
    "_id": "7z55AooBcmakvBEK-_Ql",
    "_score": 1,
    "_source": {
      "id": 1,
      "name": "Hamburg"
    }
  },
  {
    "_index": "cities",
    "_type": "_doc",
    "_id": "8D56AooBcmakvBEKM_Rk",
    "_score": 1,
    "_source": {
      "id": 2,
      "name": "Berlin"
    }
  },
  {
    "_index": "cities",
    "_type": "_doc",
    "_id": "8T56AooBcmakvBEKU_Rg",
    "_score": 1,
    "_source": {
      "id": 3,
      "name": "Cologne"
    }
  }
]

ubuntu-rs@ubuntu-rs:/workspace/git_zammad/zammad$ curl http://localhost:9200/cities/_search?q=* | jq .hits.hits[0]._source.name
"Hamburg"
```
</details>

### Support Ticket

Ticket#10133037

### Branch

`private/rs/develop/concept-rest-attribute`

```[tasklist]
### Tasks
- [ ] https://github.com/zammad/coordination-scrum/issues/85
- [ ] https://github.com/zammad/coordination-scrum/issues/86
- [ ] https://github.com/zammad/coordination-scrum/issues/87
- [ ] https://github.com/zammad/coordination-scrum/issues/88
- [ ] https://github.com/zammad/coordination-scrum/issues/89
- [ ] https://github.com/zammad/coordination-scrum/issues/90
- [ ] https://github.com/zammad/coordination-scrum/issues/92
```

**Comment by dominikklein** [comment]
@rolfschmidt @KoJie Maybe we can some more real-life use cases as an addition to the technical use case description.

**Comment by Koppishop** [comment]
### Additional Use Cases Explaination and Pain Points from Sales Perspective:

_What is your original issue/pain point you want to solve?_
- Show extended information from corresponding systems (ERP, CRM, Project Management, Article Codes, etc.) in Tickets and enable those ticket attributes to be searchable at value selection.

_Which are one or two concrete situations where this problem hurts the most?_
When this corresponding data tables are huge or changing frequently, drop down or tree select attributes are not helpfull. It could be a mess to handle assignment to specific project numbers, articles, etc. manually within a ticket. Therefore a searchable attribute to select a value is a must 

_Why is it not solvable with the Zammad standard?_
Huge Data Tables can not be handled properly with dropdown, treeselect or input attributes.

_What is your expectation/what do you want to achieve?_
Enable the agent to assign a ticket to a specific ERP/CRM article or task by searching/browsing in external database content.

**Comment by martini** [comment]
> @rolfschmidt @KoJie Maybe we can some more real-life use cases as an addition to the technical use case description.

I try to make if more specific which use cases which I got confronted in the past:

**1) Use case - ISP:**
Incoming tickets must be assigned to a server by an agent.

The server involved is stored in an additional ticket attribute. 

The possible servers are more than 20,000 and are maintained in an external data source.

**2) Use case - online shop:**
Complaint tickets to be created (or complaint tickets already created) must be linked to a purchase order.

The orders are maintained in an external system and are more than 1,000 pieces per day.

**3) Use case - service provider:**
For billing purposes, a project must be attached to a ticket. The project is identified via an additional ticket attribute.

Projects are added more and more (over the years 4000). An auto-completion would be very helpful.
