### ISSUE TITLE
Improve groups to support a more complex hierarchy

### ISSUE THREAD

**Issue by dominikklein** [zammad/zammad#4790]
### Summary (What)
As an administrator running Zammad in a company with a strong hierarchy and/or the need for strong data privacy, I want to be able to set up a profound permission system fitting the organization's structure.

As an agent working in a company with a strong hierarchy, I want to be able to search for groups to have a fast group selection. Also, I want to see the tree hierarchy during the group selection.

### Use Cases

- As a big company with a lot of departments that have also sub-teams I want to configure a comparable structure inside the group management. For example to handle the permissions in a good way and also have better ticket handling on a deeper level.

#### Additional Use Case description
**What is your original issue/pain point you want to solve?**
In case Zammad is used in bigger companies with different BusinessUnits or entirely within the company throughout 10+ departments, every BU/Department is a specific group that would need to have several sub-groups by topic or reponsability.

**Which are one or two concrete situations where this problem hurts the most?**
A Ticket needs to be assigned to a different department/BU, but as an agent I do not know the hierachy of the target group. So I need to be able to assign it to the BU/Department in general, or move through the tree and select the most logical one. In Case i know the group name but not where it is settled in the hierachie, I want to be able to search for the group name in the tree.

### Intended Outcome

As an administrator, I can create the organizational hierarchy as a tree with groups to build a more complex structure.
For example, departments with sub-departments or teams:

- Support
  - L1
    - Internal
    - External 
  - L2
    - Internal
    - External 
  - L3
    - Internal
    - External 
-  Sales
   - Pre-Sales
   - After-Sales
- Marketing
-  ...

As an agent, I can select a group inside the ticket create/edit form in an intuitive way. I'm able to see the tree structure but also search for a specific group(s). The selected group value inside the group field should show the tree (like in the multi-treeselect).

#### How will it work
In the add/edit admin dialog for groups a new field "Parent Group" (_field name needs to be defined_) where the parent group can be selected to build a hierarchy.
The group permission matrix inside the role and user add/edit dialog (and possibly other places) will no longer show all available groups inside the system. Instead, only groups with "activated" permissions are visible and new groups can be added with a new interactive group search selection.
**The permissions will not be inherited by the child groups.**
We should no longer show the group permission matrix when no `ticket.agent` permission is selected (for Users this means when no Role is selected with activated `ticket.agent`).

Inside the different conditions screens the group field needs to be changed to a multi-treeselect field.

As the first step, the group field in the ticket add/edit screen will be transformed into a "normal" tree select field. With this, it's possible to collect a group inside the tree structure or search for a group (this will be a flat structure output, with the tree information). This will currently not solve the problems with a very large amount of groups.
The single treeselect field should show the complete "tree path" as the label from the current selection (like it's done for the multi-treeselect).
Also, the "dash" for the path should be switched to a "chevron".

#### Group selection in Ticket Create

![ticket-create-group-selection](https://github.com/zammad/zammad/assets/5445094/486d5171-3b55-4324-a60a-e94a2763b6b8)

#### Group tree-select control (detail)

![group-selection-details](https://github.com/zammad/zammad/assets/5445094/6aad27d2-0cba-4141-9fe0-ee2c447187ca)

#### Group names with ancestry in Manage Groups

![group-overview-admin](https://github.com/zammad/zammad/assets/5445094/66c3f62e-5592-4d44-a32e-c065edfa7093)

#### Parent group selection in Edit Group

![group-edit-parent](https://github.com/zammad/zammad/assets/5445094/644a4083-36ec-4562-b2c5-56064bbc5bc8)

#### Permission Selection in Edit User (should be similar in Edit Role)

![group-permission-selection-role-user](https://github.com/zammad/zammad/assets/5445094/0be204a3-d0c1-417f-9f8e-9841ff3a3d24)
![group-permission-selection-role-user-2](https://github.com/zammad/zammad/assets/5445094/6155a174-33eb-4f85-9f22-2c557d3876e2)
![group-permission-selection-role-user-3](https://github.com/zammad/zammad/assets/5445094/a4f31f89-e562-43ce-8cd0-2d0c2553b9dd)
![group-permission-selection-role-user-4](https://github.com/zammad/zammad/assets/5445094/cf67095c-da2a-4c4b-b134-98f36b503254)

```[tasklist]
### Tasks
- [ ] https://github.com/zammad/coordination-scrum/issues/76
- [ ] https://github.com/zammad/coordination-scrum/issues/77
- [ ] https://github.com/zammad/coordination-scrum/issues/78
- [ ] https://github.com/zammad/coordination-scrum/issues/79
- [ ] https://github.com/zammad/coordination-scrum/issues/80
- [ ] https://github.com/zammad/coordination-scrum/issues/81
```

Please keep in mind that we should try to fix when we are changing the permission table output: https://github.com/zammad/zammad/issues/4570

**Comment by Koppishop** [comment]
**Further thoughts from the sales view:**

_What is your original issue/pain point you want to solve?_
In case Zammad is used in bigger companies with different BusinessUnits or entirely within the company throughout 10+ departments, every BU/Department is a specific group that would need to have several sub-groups by topic or reponsability. 

_Which are one or two concrete situations where this problem hurts the most?_
A Ticket needs to be assigned to a different department/BU, but as an agent I do not know the hierachy of the target group. So I need to be able to assign it to the BU/Department in general, or move through the tree and select the most logical one. In Case i know the group name but not where it is settled in the hierachie, I want to be able to search for the group name in the tree.

_Why is it not solvable with the Zammad standard?_
Within the "singleselect" field it is not convenient to handle a huge number of group and sub-groups. A Ticket needs to be assigned within a tree-select and group need to be seachable in Assignment process by the agent.  

_What is your expectation/what do you want to achieve?_
Enable the agent to assign every ticket to the corresponding group and assist in group selection or tree navigation as good as possible to reduce time consumption. The more divers the group achritecture is, the more benefit the agents will have through a good solution.

_Additional Aspects (When you start Feature Enhancement, think about this)_
1) I know the responsible agent, but not the correct group:
In this case it would be great, if the owner/agent field is searchable as well. If I find my agent of choice, the group selection is automatically reducing options by the selected_owner permissions.

2) I am the owner of the master ticket and need to split away some processes in a sub-tasks:
In this case it would be great, if I would get the possibility to get subscribed on the sub-tickets I have created and I could keep read permissions on those tickets. For case escalations a dedicated es
 
3) I am the teamleader or manager and responsible for a node in the group tree select hierachy:
In this case I would like to be able to configure text modules and makros for my groups only. Furthermore I want see reports of my departments only, create Tiggers/Schedulers and Core Workflows for my responsability as well. 
To achieve this, the admin section of roles needs to offer categories to limit access permissions by Group-Tree.

**Comment by YetAnotherGerrit** [comment]
I was asked four questions:

**What is your original issue/pain point you want to solve?**

There are several UI elements that are not useable with a large amount of groups:
- Drop-Down in Ticket-Create/View
- Group manager
- Drop-Down when configurering Trigger/Scheduler/Makros/Core Workflows, etc.

**Which are one or two concrete situations where this problem hurts the most?**

See above.

**Why is it not solvable with the Zammad standard?**

Because 8000 entries in a drop-down cannot be avoided, when you have 8000 groups.

**What is your expectation/what do you want to achieve?**

Make Zammad useable in that scenario.

**Comment by dominikklein** [comment]
> **What is your original issue/pain point you want to solve?**
> 
> There are several UI elements that are not useable with a large amount of groups:
> 
>     * Drop-Down in Ticket-Create/View
> 
>     * Group manager
> 
>     * Drop-Down when configurering Trigger/Scheduler/Makros/Core Workflows, etc.
> 
> 
> **Which are one or two concrete situations where this problem hurts the most?**
> 
> See above.
> 
> **Why is it not solvable with the Zammad standard?**
> 
> Because 8000 entries in a drop-down cannot be avoided, when you have 8000 groups.
> 
> **What is your expectation/what do you want to achieve?**
> 
> Make Zammad useable in that scenario.

This is for sure a problem that needs to be solved in the future, but this enhancement here is the first iteration and does not include a solution for this amount of groups. But it's only the first step.

**Comment by mgruner** [comment]
If we use a chevron sign, we will get problems with LTR languages.

**Comment by dominikklein** [comment]
> If we use a chevron sign, we will get problems with LTR languages.

Yes, we need to have this in mind, but I think something we can solve because we are also already using the chevron sign in the treeselect context. When I see it correctly the current output which we want to improve with this chevron sign, is already not that optimal for the LTR situation.
