### ISSUE TITLE
Improve UX for tree select field in desktop app

### ISSUE THREAD

**Issue by dvuckovic** [zammad/zammad#4830]
### Used Zammad Version

6.1

### Environment

- Installation method: any
- Operating system: any
- Database + version: any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

Interaction with the tree select field in the desktop app results in bad UX due to a couple of interaction issues (see below).

### Expected behaviour

Tree select field in desktop app should provide UX comparable to other modern apps. Normal usage should not be affected by the unexpected and strange behavior during interaction with the control.

### Steps to reproduce the behaviour

Several UX issues should be addressed, they are collected below:

1. Clicking on a field with/without a selection opens the dropdown but requires the user to clear the search field if they want to filter for options. Either an empty selection marker `-` or the selection label are initially shown in the search field and keyboard cursor is rendered at the far end of it.
   ![1](https://github.com/zammad/zammad/assets/6049445/f00ff3ac-ade3-4c37-ae0a-5e54ba3b7618)
   Consider clearing the search field whenever the dropdown is opened while leaving the keyboard focus in it so the user can immediately enter their search terms. Current selection can be highlighted diferently in the dropdown, i.e. by rendering a checkmark icon or changing the style of the selected option.
   _This is not applicable to multi-select field, since it shows current selection as a token pill and does not interfere with the search._

2. Selecting a value leads to a different selection depending on the location of the option. If the selection is chosen by navigating through the dropdown menu, its label will be taken from the selected option only. If the selection is chosen by clicking on a search result, its label will consist of the selection option and complete path of its parent.
   ![2](https://github.com/zammad/zammad/assets/6049445/4fda4ea9-16b2-4b3f-afb9-116f96c8d916)
   Consider rendering the selected label in a consistent way, i.e. always showing its full path separated by chevrons.
   _This is not applicable to multi-select field, since it shows current selection in a token pill with the full path separated by chevrons._

3. Clicking on a dropdown option on the left side of the menu will both select that option and navigate to the child panel if available. Only clicking on the right side of the menu (near the right arrow) will just switch the panel without selecting the option. This may result in multiple value changes which in turn trigger core workflow requests with undesired state.
   ![3](https://github.com/zammad/zammad/assets/6049445/4f8f9d5b-fef7-4dbb-9b90-3f9091ed2733)
   Consider separating the selection from the navigation so that clicking on the left side of the menu will only select the option, while clicking on the right side will still only navigate to the child panel. The buttons should be rendered and highlighted in a split fashion, so the user immediately knows what will happen upon clicking. Also consider closing the dropdown upon selection for single selects, and keeping it open for multi selects.
  Also: The selection row should be split into two buttons for parent nodes.
      * The left button (wider) is for selecting the option only, in case it's enabled.
      * The right button (square) is for navigating to the parent menu, proposed highlight color change to green.

4. Searching for an option and then leaving the field will preserve the search input and results the next time the field is open. This requires searching for something else and then clearing the input for the original list to pop up again. One too many backspaces in multi select field may also lead to loss of current selection.
   ![4](https://github.com/zammad/zammad/assets/6049445/63eda2e2-47d8-4e3e-88af-3ddc520249df)
   Consider clearing the search input whenever the field is closed, incl. if no selection occurs.

5. When navigating by keyboard, selecting an option does not „blur“ the field properly. This prevents some other buttons from being clicked and requires „double click“.

6. Inactive parent nodes are displayed in a ~~strikethrough~~ style, but they can still be browsed for their active children. 
   Consider using an alternative style for inactive parents, i.e. a transparent disabled state that prevents them from being selected.

7. Very long group names break the UI in multiple selection fields (e.g. Overviews, SLAs, Triggers, Schedulers, Timeaccounting, Auto-Assignment):
![image](https://github.com/zammad/zammad/assets/60067527/67e10fb8-b007-4330-91b8-f937af67746c)
In tokenized input fields, it works:
![Screenshot from 2023-09-28 11-20-53](https://github.com/zammad/zammad/assets/60067527/42a2a96a-2f49-4c4b-bce7-51581124aac6)

### I'm sure this is a bug and no feature request or a general question.

yes
```[tasklist]
### Tasks
- [x] Clear the search input when focusing the field
- [x] Add a checkmark icon to the currently selected option
- [x] Render the selected label with its full path incl. chevrons
- [x] Split options into two buttons for selection and navigation
- [x] Close the dropdown upon selection for single selects, keep it open for multi selects
- [x] Clear the search results on dropdown close
- [x] Add implicit blur on keyboard navigation
- [x] Change display style of inactive parent nodes
- [x] ~~Fix overflowing selections in multi selects~~ not reproduced!
- [x] Provide a dedicated button for clearing of the value in autocomplete fields
- [x] Check the contrast of disabled parent nodes in light mode
- [x] Fix console errors on keyboard navigation of multiselect fields
- [x] Fix multi select search issue during selection
- [ ] Clarify the navigation control bar look
- [x] Tests
```

**Comment by dvuckovic** [comment]
Refinement 2023-09-29:

* The selection row should be split into two buttons for parent nodes.
  * The left button (wider) is for selecting the option only, in case it's enabled.
  * The right button (square) is for navigating to the parent menu, proposed highlight color change to green.

**Comment by fliebe92** [comment]
@dvuckovic we need to take https://github.com/zammad/zammad/issues/4853 into consideration as well, IMO.

**Comment by dvuckovic** [comment]
@fliebe92 #4853 is a confirmed regression of #4836, the fix is imminent.
