### ISSUE TITLE
Cannot select a group in Ticket bulk update

### ISSUE THREAD

**Issue by mantas** [zammad/zammad#4836]
### Used Zammad Version

6.2

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version: any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

Group cannot be selected in Tickets bulk update. Dropdown is not visible.

![Screenshot 2023-09-26 at 11 54 56](https://github.com/zammad/zammad/assets/36944/5d3f14ce-d356-408f-924f-c49f5d5d62e0)
![Screenshot 2023-09-26 at 11 55 00](https://github.com/zammad/zammad/assets/36944/32400c4f-1715-4415-82ad-f9e8030d9caa)

### Expected behaviour

Group can be selected in Tickets bulk update.

### Steps to reproduce the behaviour

- Go to any overview
- Select a ticket
- Try to select a new group in bulk update form

### I'm sure this is a bug and no feature request or a general question.

yes
```[tasklist]
### Tasks
- [x] Field is aligned correctly
- [x] Dropdown is visible and options can be selected
- [x] Tests
- [x] Cranky animation when moving from submenus with different amount of items
```

**Comment by YetAnotherGerrit** [comment]
Came here to create this issue, so just a 👍 :-)

**Comment by dvuckovic** [comment]
Confirmed regression in #4853, the fix is imminent.
