### ISSUE TITLE
Data retention rules for cleanup users (or other objects) from the system with the scheduler

### ISSUE THREAD

**Issue by dominikklein** [zammad/zammad#4838]
### Summary (What)

Companies have to comply with data privacy rules to delete all customer information that is saved in Zammad after a specified time and specific conditions. 
At the moment Inside Zammad, you can add manually a deletion task for one specific user inside the data privacy area (this means manually searching for the specific user and adding this task).
The administrators have to manually check e.g. how old tickets are and add a deletion job for that specific customer. In bigger companies you have to do that many times - this is not scalable and hard to realize.

#### Which are concrete situations where this problem hurts the most?
- When you as an agent need to find and hand over relevant customers manually to your admin and ask him to delete that. There are many workarounds needed to filter those customers and manage the handover. That's not easy & intuitive.
- When you as an administrator get a list with many customers to get deleted every day. This consumes a lot of time
- When you as a customer want to be sure that your data gets deleted. But since the current manual deletion is error-prone, 100% security cannot be guaranteed here.

#### Why is it not solvable with the Zammad standard?
There are two possibilities to follow your data protection and retention obligations via the admin interface at the moment:
1) To delete tickets automatically you can build a scheduler (but with this, you still have the user data) - but currently for tickets you don't have a history of the deleted tickets.
2) To delete the user data you need to set up a deletion job manually for a specific user.

### Use cases

- Wholesale:
A customer orders something from the wholesale online store and does not want to create a customer account. The order is processed and successfully closed. After the last contact with the customer has been made, the entire reference, including customer data, is to be deleted after 6 months (according to contractually regulated data protection and retention obligations).

- Survey for a retail store:
The craft store "Papierfrosch" collects feedback via a web form. There, customers can also specify whether their information should be deleted after two weeks. Zammad has its own attribute for this. When the emails have been processed by the web form, they are automatically deleted.

- Works Council requirements:
The Works Council has strict privacy requirements for sick calls processed through Zammad, all those tickets that are in the "sick call" category and are processed must be deleted after one month. 

- Cleanup of users who no longer have any tickets in the system.

### Intended Outcome

An administrator should be able to enter rules into Zammad once according to his company's privacy and retention policies so that the user data (or other object data, e.g. tickets) is automatically deleted with a history of the deleted data.

For this such rules need to be available for user conditions:

- Filter for Roles
- Last login time
- Last contact - latest timestamp from the customer's tickets.
- Last contact (Agent)- latest timestamp from the customer's tickets.
- Last contact (Customer)- latest timestamp from the customer's tickets.
- Ticket count or only Existing tickets yes/no?
- Open ticket count or only Existing open tickets?
- Last update time on their tickets

Additional organization conditions:
- no related customers

For this, it should be possible to use additional objects (=user and organization) inside the current scheduler.
The new objects should support the normal conditions for their own attributes (and for the user also the defined conditions on the side of the list).
Currently for the scheduler actions only changing the values (for users no restricted data should be changeable, e.g. login or password) and adding a data privacy deletion task should be possible.
The ticket actions should be extended with a "data privacy deletion task" action.

Optional:
- Possibility to trigger a webhook for syncing the data to an external system (for this the webhook part would need improvement).

### Technical Implementation

The scheduler needs to be extended with an additional object selection field (similar to core workflow). The default object should be a ticket.
After selecting an object, the conditions and actions will be related to the selected object.

The following objects should be available: `ticket`, `user`, and `organization`.

![Bildschirmfoto 2023-09-27 um 10 57 52](https://github.com/zammad/zammad/assets/5445094/57d58d45-859d-4556-a727-d313e53d9285)
![Bildschirmfoto 2023-09-27 um 10 57 26](https://github.com/zammad/zammad/assets/5445094/c370bb4b-250c-467f-ad68-0cade947c2b6)

#### Backend

Inside the backend, we need to move the current ticket SQL selector/condition solution so that all objects can benefit from some "base" implementation in the future. Here we need to check how joins and other things need to be solved.
Also, some base for the actions should be added (when possible) and only special actions should be inside the objects.
For sure every object will have special situations that need to be solved.

#### Documentation

Check what is currently happening, when ticket customer relation was changed during the ticket flow -> Maybe we should add some hints in the documentation.

```[tasklist]
### Tasks
- [ ] https://github.com/zammad/coordination-scrum/issues/97
- [ ] https://github.com/zammad/coordination-scrum/issues/98
- [ ] https://github.com/zammad/coordination-scrum/issues/99
- [ ] https://github.com/zammad/coordination-scrum/issues/101
- [ ] https://github.com/zammad/coordination-scrum/issues/102
- [ ] https://github.com/zammad/coordination-scrum/issues/103
```
