### ISSUE TITLE
Enhance usage of Zammad shortcuts (cross browser and cross platform)

### ISSUE THREAD

**Issue by Mirtaaa** [zammad/zammad#4870]
### WHAT
The Zammad Shortcuts are currently not working properly depending on the browser and the OS. For this reason, many users have given up on using them at all. Other shortcuts (like systen or browser shortcuts) are overriding the zammad shortcuts.
For some users, it even compromises workflows, when specific Zammad shortcuts are colliding with browser shortcuts etc.
There is a complexity to this problem due to high number of combinations of OS and Browsers to avoid colliding shortcuts.

### USE CASES:
1. I want to Enable/disable inline translations quickly
2. I want to switch to the next Zammad tab with a button push
3. I want to switch to the next opened tab within Zammad without using the mouse.
4. I want to easily navigate in Zammad (e.g. between overview and ticket detail view) by using my keyboard.
5. I want to quickly and easily change the ticket status

### ACCEPTANCE CRITERIA
- only single keys/ simple shortcuts are used
- editing shortcuts stay the same (may change in new TS)
- Add a switch from new to old shortcuts for getting-used-to Period

### MOCKUPS

<a title="Modal (enabled)" href="https://github.com/user-attachments/assets/a24598c8-2da2-4d30-aca6-9622fc1134e5" target="_blank"><img width="180" alt="ModalEnabled" src="https://github.com/user-attachments/assets/950a5341-c0f5-4af7-bbb7-456fc27e0eba"></a> <a title="Modal (disabled)" href="https://github.com/user-attachments/assets/abd95eef-0adf-4e39-8a97-a32eb8bcc2a4" target="_blank"><img width="180" alt="ModalDisabled" src="https://github.com/user-attachments/assets/abd95eef-0adf-4e39-8a97-a32eb8bcc2a4"></a>

____________________________________________________

IDEAS:
- ~customizable shortcuts (Admin level)~
- ~command box (small popup- enter command)~
- single keys / Simple shortcuts

- what about accessibility? Do they need to be possible to disable / customizable?
   - https://www.bit-inklusiv.de/bitv-softwaretest/2-1-4-tastatur-kurzbefehle-abschaltbar-oder-anpassbar/
```[tasklist]
### Tasks
- [x] Move the toggle for keyboard shortcuts enable to the modal - DV
- [x] Implement switch to old style shortcuts and store the setting in the local storage - TT
- [x] https://github.com/zammad/zammad/issues/4324 - DV
- [x] Tests - DV
```

**Comment by ralf401** [comment]
While editing the section "Keyboard Shortcuts" in the user-documentation, I made some tests with Firefox (F) and Chrome (C). 

System:
Fedora 38
Firefox 118.0.1
Chrome: 117.0.5938.149

Here my findings and the overview to check the intended function:

- `shift` + `ctrl` + `n` => opens a new incognito window (C only)
- `shift` + `ctrl` + `w` => closes the complete browser window (F+C)
- `shift` + `ctrl` + `tab` => switches browser tabs (F+C)
- `shift` + `ctrl` + `shift+tab` => how to press shift twice? Not tested.
- `shift` + `ctrl` + 3x `.` => not working  in F
- `shift` + `ctrl` + `t` => creates a new tab in C
- `shift` + `ctrl` + `g` => not working (F+C)
- `shift` + `ctrl` + `←` /  `→` => not working (F+C)

![image](https://github.com/zammad/zammad/assets/60067527/f47ef855-439f-482b-b197-18ceb594b1b2)

Just to be complete I mention the [draft PR ](https://github.com/zammad/zammad-user-documentation/pull/192)for the documentation here.

**Comment by Mirtaaa** [comment]
Here are some more current status findings from Bozo
[shortcuts (1).zip](https://github.com/zammad/zammad/files/12889375/shortcuts.1.zip)

**Comment by martini** [comment]
Related https://github.com/zammad/zammad/issues/4708, https://github.com/zammad/zammad/issues/4324

**Comment by gwingend** [comment]
Guten Tag,

vielen Dank für Ihre E-Mail.
Ich bin nicht im Büro.
Ihre Mail wurde weder gelesen noch weitergeleitet.

Bitte wenden Sie sich in dringenden Fällen an den EDV-Helpdesk ***@***.***).


Mit freundlichen Grüßen
Gerhard Wingender
Amt für IT

>>> Martin Edenhofer ***@***.***> 29.1.24 17:03 >>>

Related https://github.com/zammad/zammad/issues/4708, https://github.com/zammad/zammad/issues/4324

-- 
Reply to this email directly or view it on GitHub:
https://github.com/zammad/zammad/issues/4870#issuecomment-1915019153
You are receiving this because you are subscribed to this thread.

Message ID: ***@***.***>
-- 
Diese E-Mail wurde von Sophos UTM auf Viren überprüft.

Besuchen Sie uns im Internet unter: www.neuwied.de
oder bei Facebook @neuwied.de
und Instagram @deichstadt_neuwied

Eine E-Mail unterliegt dem Kommunikationsgeheimnis und ist nur für den Empfänger bestimmt. Der Inhalt ist grundsätzlich als vertraulich zu betrachten und nicht für Dritte zugänglich. Eine Weiterleitung bedarf daher der Zustimmung des Verfassers. Diese E-Mail darf zu dienstlichen Zwecken innerhalb der Stadtverwaltung weitergeleitet werden.

Sparen Sie pro Seite ca. 200 ml Wasser, 2 g CO2 und 2 g Holz: Drucken Sie daher bitte nur, wenn es wirklich notwendig ist!

**Comment by martini** [comment]
Solution proposal:

Advantage of the new implementation: Works in all browsers (will fix https://github.com/zammad/zammad/issues/4708 and https://github.com/zammad/zammad/issues/4324 too).

Change for users: Shortcuts also work without hotkeys (such as `ctrl+alt`) in the entire application (shortcuts work with single key).

Old shortcuts:
<img width="1440" alt="Screenshot 2024-02-29 at 11 49 05" src="https://github.com/zammad/zammad/assets/110226/85d2ae05-1b02-4c3b-8344-5c466069680c">

New shortcuts:

<img width="1440" alt="Screenshot 2024-02-29 at 11 48 00" src="https://github.com/zammad/zammad/assets/110226/2b93e612-94c0-4f04-8d38-ea27f417b1cd">

**Comment by forreggbor** [comment]
The shortcuts still not compatible with browsers. For example inline translation. Will it be fixed?
We use this version: 6.3.1-1722948970.e504ff79.jammy

**Comment by dvuckovic** [comment]
@forreggbor Yes, this was fixed. The changes are coming in Zammad 6.4 soon.
