### ISSUE TITLE
Translation Management Improvements

### ISSUE THREAD

**Issue by mgruner** [zammad/zammad#4875]
Assignees: @dvuckovic @vBenTec @dominikklein 

### WHAT

- The current translation management screen has a very bad UX.
- Users cannot specify via UI if an object attribute should be translatable or not.
- Users cannot add custom strings to the translation table manually via the UI, so that they are not able to translate custom translatable object attributes, states etc. (especially in Hosted, where console is not available)

### Use-Cases

- As a company that is working together with third parties during the ticket lifecycle I want to set a special pending state "waiting on third-party" or to add additional priorities. Because inside the company we have different locations we also need the possibility to translate the state or priority. Currently, the possibilities are limited here inside the admin interface.

- In our internal IT we have a categorization tree for the incoming tickets which needs also to be translated, because of employes from different countries.

- My company is using the Zammad-Hosted product and I'm not able to add custom translation strings with the rails console.

### HOW

- ~~Make `translate` flag of object attributes configurable via UI.~~ Already the case
- Rewrite the translation management screen for improved usability.
- New possibility to add custom translation strings via UI.
- Implement a suggestion feature to locate untranslated strings from translatable object attributes, state and overview names etc. and make it easy to translate them via UI.

### Intro

<img width="1920" alt="274225796-253aad2f-23ee-4b60-b75d-a15f2f9ed83d" src="https://github.com/zammad/zammad/assets/211281/dda0a276-37d9-4dd6-b6ef-93c13f11a1bb">

### Description Modal

<img width="1920" alt="274225858-bef44650-a525-40d1-8471-1a45e5ff8e17" src="https://github.com/zammad/zammad/assets/211281/00ae9bd8-fb66-490b-a885-f453ad069553">

### Adding New Translation

<img width="1920" alt="274523387-c2e1ad9c-e7c0-4052-bc96-9dea5fbe883c" src="https://github.com/zammad/zammad/assets/211281/40f0df2b-39cd-411d-9084-c571ccd9cf9a">

### Filtering Suggestions

<img width="1920" alt="274523445-e87fa0c1-23d4-4264-9f30-dcf83a5bc4ae" src="https://github.com/zammad/zammad/assets/211281/6d0afea5-effa-4c00-a0e1-7a49908df774">

### Overview Table (System Translation)

<img width="1920" alt="274226257-f31ef234-6a36-4651-9c1a-05f0cfde8828" src="https://github.com/zammad/zammad/assets/211281/f30cb274-e57c-4339-a909-e782de0d5166">

### Overview Table (Custom Translation)

<img width="1920" alt="274226371-3ad7715e-2b2b-49a1-90b3-1fa340c99d40" src="https://github.com/zammad/zammad/assets/211281/0f307f35-d5b3-4ffe-9aaf-0b6c48c48f04">

## User Stories

- As an administrator, I can
  - specify if an object attribute should be translatable or not via UI 
  - customize translation strings in a user friendly way
  - add new translation strings via UI
  - receive suggestions for translations based on missing translations of translatable strings from object attributes etc.
```[tasklist]
### Tasks
- [x] Drop old screen and cleanup underlying controller - DV
- [x] Add welcome screen and description dialog - DV/BS
- [x] Translation table screen - BS
- [x] Add custom add/edit modals with mocked data - DV
- [x] Add endpoint for list custom translation - DK
- [x] Add search endpoint for locale and filter - DK
- [x] Connect string suggestions to front end - DV
- [x] Add create or update endpoint - DK
- [x] Add reset endpoint for a single record - DK
- [x] Reset and remove operations with confirmation dialogs - BS
- [x] Use upsert endpoint when form is submitted - DV/BS
- [x] Backend for string suggestions - DV/DK
- [x] Align edit mode with agreed style by disabling fields and removing suggestions table - BS
- [x] Align suggestions table with new type column and show a warning when a system translation is chosen - DV
- [x] Switch to textareas for source and target fields - DV
- [x] Tests - BS/DK/DV
```
