### ISSUE TITLE
Checklists / To-do lists

### ISSUE THREAD

**Issue by Mirtaaa** [zammad/zammad#4886]
### WHAT
Currently, creating simple checklists/to-do lists in Zammad is impossible. This leads to very time-consuming workarounds and/or to outsourcing to other tools. It interrupts the user’s workflow in Zammad and makes the process inconvenient.  

### USE CASES
**a.** Customers sometimes can’t immediately provide all necessary information for a request, therefore, I need to track what information has already been provided and which one is still open/missing.

**b.** Requests from clients require the check of a procedure of 10 or more steps & some work procedures require to be done in a specific order. I want to create Templates for specific To-do’s and use them accordingly, depending on the request.

**c.** A customer has a complaint about the operation of some services, now I need a list of several things to check, to see if there is a possible problem, before transferring a ticket to higher-level support.

**d.** I want to create simple work orders which are basically a number of standard to-dos and it is important that I carry out all to-dos on the list. To manage these to-dos, I want to use checklists.

**e.** OnBoarding: We’d like to keep records of the platforms a user has been granted access to. / OffBoarding: Whenever someone leaves the organization, we need to lock accounts and clean up all over the place, as well as have a record of what has been done and who has done it. We want to make sure that we don’t miss any of the steps.

**f.** I need to make sure, everything is checked when a technical error occurs. I want to check a list of common mistakes.

### Intended Outcome
Have checklists inside the Tickets / connected to tickets
Have the possibility to create/store “Checklist Templates” to pick accordingly the needed template for each ticket

### Actual behaviour
Checklists for each ticket are outsourced to another tool.

### ACCEPTANCE CRITERIA / USER STORIES

- Creating multiple checklist templates in the admin area of Zammad, each consisting of a series of checklist items
- Adding one checklist to an existing ticket
- ~Adding multiple checklists to an existing ticket~
- Checking/(unchecking) items on the checklist within a ticket
- ~Adding a note to a specific checklist item / add additional description/comment to a single checklist item~
- Visibility into who (un)checked in a checklist item and when
- Warning when trying to close a ticket that still has unchecked checklist items 
 -> needs to also apply to closed states (for example pending close)
- ~Assigning checklist templates to groups (multi-select allowed if possible)~
- option to link a ticket to a Checklist Item / Ticket references 
  -> When ticket is closed, Checklist Item is checked off automatically
(Use case rami.io: doesn't solve problem with the note)

***NOTE**
To combine Checklists or even Checklist Tasks with Processes or workflows might create a high complexity, and also having dependencies between checklists as well. 
**Decision for simple checklist - no trigger/CWF/...**

#### Admin

<a href="https://github.com/user-attachments/assets/1b68faeb-638b-4fe9-8888-c66f1c357e6f" target="_blank"><img width="180" title="01-Intro" alt="01-Intro" src="https://github.com/user-attachments/assets/1b68faeb-638b-4fe9-8888-c66f1c357e6f"></a> <a href="https://github.com/user-attachments/assets/000e3745-b8b7-41e6-a8f4-aeb73083eac5" target="_blank"><img width="180" title="02-Add" alt="02-Add" src="https://github.com/user-attachments/assets/000e3745-b8b7-41e6-a8f4-aeb73083eac5"></a> <a href="https://github.com/user-attachments/assets/f3c0bccf-b5d2-4119-b2b4-f7d7f74eb175" target="_blank"><img width="180" title="03-AddPopulated" alt="03-AddPopulated" src="https://github.com/user-attachments/assets/f3c0bccf-b5d2-4119-b2b4-f7d7f74eb175"> <a href="https://github.com/user-attachments/assets/25eb75e4-c435-4f72-8443-490784e54bce" target="_blank"><img width="180" title="04-Added" alt="04-Added" src="https://github.com/user-attachments/assets/25eb75e4-c435-4f72-8443-490784e54bce"></a> <a href="https://github.com/user-attachments/assets/1ade4879-49d4-4f2f-9724-bf9daeb8441e" target="_blank"><img width="180" title="05-Edit" alt="05-Edit" src="https://github.com/user-attachments/assets/1ade4879-49d4-4f2f-9724-bf9daeb8441e"></a> <a href="https://github.com/user-attachments/assets/06324949-27ec-47d1-9384-0f654ba11cbd" target="_blank"><img width="180" title="06-Overview" alt="06-Overview" src="https://github.com/user-attachments/assets/06324949-27ec-47d1-9384-0f654ba11cbd"></a>

#### Ticket Zoom (currently it's not planned for mobile view)

<a href="https://github.com/zammad/zammad/assets/6049445/f7dc2582-aa5f-4570-ab9d-69ba40d7a90d" target="_blank"><img width="180" title="07-TicketAttributes" alt="07-TicketAttributes" src="https://github.com/zammad/zammad/assets/6049445/f7dc2582-aa5f-4570-ab9d-69ba40d7a90d"></a> <a href="https://github.com/zammad/zammad/assets/6049445/d438ce92-bd2e-41d0-a366-e3b2a4e7a5b3" target="_blank"><img width="180" title="08-SidebarWithoutTemplates" alt="08-SidebarWithoutTemplates" src="https://github.com/zammad/zammad/assets/6049445/d438ce92-bd2e-41d0-a366-e3b2a4e7a5b3"></a> <a href="https://github.com/zammad/zammad/assets/6049445/4dc47e7c-4dc3-4187-b396-61d5db563e5d" target="_blank"><img width="180" title="09-SidebarWithTemplates" alt="09-SidebarWithTemplates" src="https://github.com/zammad/zammad/assets/6049445/4dc47e7c-4dc3-4187-b396-61d5db563e5d"></a> <a href="https://github.com/zammad/zammad/assets/6049445/27673fed-5331-4c53-969a-67ef0ba36b9e" target="_blank"><img width="180" title="10-SidebarEmpty" alt="10-SidebarEmpty" src="https://github.com/zammad/zammad/assets/6049445/27673fed-5331-4c53-969a-67ef0ba36b9e"></a> <a href="https://github.com/zammad/zammad/assets/6049445/6e8feec4-5832-41aa-9467-7e7b6909ca4b" target="_blank"><img width="180" title="11-SidebarFirstEntryPopulated" alt="11-SidebarFirstEntryPopulated" src="https://github.com/zammad/zammad/assets/6049445/6e8feec4-5832-41aa-9467-7e7b6909ca4b"></a> <a href="https://github.com/zammad/zammad/assets/6049445/bc0e8bd6-ddf1-4dee-9e76-5963dff9e26b" target="_blank"><img width="180" title="12-SidebarFirstEntryAdded" alt="12-SidebarFirstEntryAdded" src="https://github.com/zammad/zammad/assets/6049445/bc0e8bd6-ddf1-4dee-9e76-5963dff9e26b"></a> <a href="https://github.com/zammad/zammad/assets/6049445/0266f199-b569-41cd-afcf-739481063bb1" target="_blank"><img width="180" title="13-SidebarSecondEntryAdded" alt="13-SidebarSecondEntryAdded" src="https://github.com/zammad/zammad/assets/6049445/0266f199-b569-41cd-afcf-739481063bb1"></a> <a href="https://github.com/zammad/zammad/assets/6049445/880387f4-83f3-48e8-9216-a75b5ca6536f" target="_blank"><img width="180" title="14-SidebarAllAdded" alt="14-SidebarAllAdded" src="https://github.com/zammad/zammad/assets/6049445/880387f4-83f3-48e8-9216-a75b5ca6536f"></a> <a href="https://github.com/zammad/zammad/assets/6049445/ae9f45b1-a909-4311-a208-d8d6c43b02d5" target="_blank"><img width="180" title="15-SidebarReorderMode" alt="15-SidebarReorderMode" src="https://github.com/zammad/zammad/assets/6049445/ae9f45b1-a909-4311-a208-d8d6c43b02d5"></a> <a href="https://github.com/user-attachments/assets/fa51f158-c82c-4c48-970e-a69f3eba9d3f" target="_blank"><img width="180" alt="16-SidebarEmptyState" src="https://github.com/user-attachments/assets/fa51f158-c82c-4c48-970e-a69f3eba9d3f"></a> <a href="https://github.com/user-attachments/assets/c2f86913-25dc-4c96-b7a2-b8435d8b0ba9" target="_blank"><img width="180" alt="17-SidebarEmptyReadonlyChecklist" src="https://github.com/user-attachments/assets/c2f86913-25dc-4c96-b7a2-b8435d8b0ba9"></a> <a href="https://github.com/user-attachments/assets/2a9e7d10-0dc7-4cb5-9e3e-d3932c35e490" target="_blank"><img width="180" alt="18-SidebarChecklistReadonly" src="https://github.com/user-attachments/assets/2a9e7d10-0dc7-4cb5-9e3e-d3932c35e490"></a> <a href="https://github.com/user-attachments/assets/15b5a496-7d41-4d71-9568-8b4ae1ba6ca3" target="_blank"><img width="180" alt="19-TicketCloseModal" src="https://github.com/user-attachments/assets/15b5a496-7d41-4d71-9568-8b4ae1ba6ca3"></a>

```[tasklist]
### Tasks
- [ ] https://github.com/zammad/coordination-scrum/issues/174
- [ ] https://github.com/zammad/coordination-scrum/issues/175
- [ ] https://github.com/zammad/coordination-scrum/issues/176
```

**Comment by rolfschmidt** [comment]
Note: If you want to have impact via triggers, schedulers and especially core workflow, then you should consider putting this check list stuff into an object manager attribute.

Else I hardly see to support it via core workflow. E.g. if you edit the ticket then you have a temporary state of the ticket and core workflows is working form-based which means it would be very hard to make this possible via a separate sidebar widget for example. 

Also, if the checklist is no ticket attribute then it will be hard to use it as conditions or actions in the triggers or schedulers.

**Comment by st31ny** [comment]
What about adding a checklist item on the fly? In our use case customer requests sometimes require an additional, non-standard step that cannot be completed immediately.

**Comment by graf0** [comment]
imho ticket list checking/unchecking could be just hidden entry in ticket history. The clue of feature is: checklist should be visible in one place, not scattered over ticket with more and more fields checked in each comment.

**Comment by West-88** [comment]
What would it cost to developed that feature? What’s the price range?

**Comment by Koppishop** [comment]
> What would it cost to developed that feature? What’s the price range?

The easiest way would be if you send a short email to enjoy@zammad.com, then we can discuss the quote and sponsoring process and how you can participate on the development and partially sponsor this feature.
