### ISSUE TITLE
Possibility to add custom ticket priorities

### ISSUE THREAD

**Issue by ralf401** [zammad/zammad#4892]
### Summary (What)

The complexity of the choosable priorities of tickets is not enough for some customers.
For example, if they have more than 3 escalation levels,  the current priorities (`1 low`, `2 normal`, `3 high`) aren't sufficient.

**Why is it not solvable with the Zammad standard?**
Currently, it is solvable in Zammad standard, but via the Rails Console. 

This brings two problems:

- Self-hosted customers often lack the knowledge to issue cryptic commands. The result is misconfigurations.
- Hosted Customers -> Here the support (L1 and L2) is involved. There is usually some need for clarification here (between customer and L1 and then often also between L1 & L2).) Self-hosted customers often lack the knowledge to issue cryptic commands. The result is misconfigurations.

**Typical problems with the current approach are:**

- In which language should the priority be called what?
- What about the colors of the priority?
- What about the additional icon of the priority?

**What is your expectation/what do you want to achieve?**

Users should be able to manage ticket priorities themselves in Zammad through the admin interface.

### Use cases for the feature idea.

**Use Case 1:**
For our customers, it is really important, that our product is running without any problem. If this is not the case, we have to pay high penalties for the non-availability of service. Because the service can also be partially unavailable, we need fine-grained priorities to react in the best possible and fastest way. 

**Use Case 2:**
We are migrating from another system to Zammad and have 5 priority levels so far. We want to keep it and be able to manage them in the admin interface.

### Intended Outcome

It should be possible to add new ticket priorities in the admin area. Also, it should be possible to edit existing (e.g. default ticket priorities) inside this section. The default ticket priority for ticket creation and follow-ups should be configurable. The priorities have to be translatable.

### Technical implementation

- Permission for the new admin area should be added (like we have for the other admin areas). Here we will reuse the `admin.object` permission because it's already used in the existing ticket state controller.
- The creation of a new ticket priorities should be intuitive (e.g. it should be understandable which colors and icons should be used for the current use case). Maybe some description or use case examples for the field?
- The "default" for new Tickets has to be configurable
- Ticket priorities require the following attributes during editing:
  - Name
  - UI color (currently available: `low-priority`, `high-priority`)
  - UI icon (currently available: `low-priority`, `important`) - (behind `ui_ticket_overview_priority_icon` setting)
  - Active
  - Default create (on list level available to make it clear that only one item can be selected)
  - Note

Clarification:
- Should there be a fixed list for UI-Color/UI-Icon or some more generic possibilities?
- When possible we should add a link inside the object manager attribute modal to the other admin areas.
- At which location do we want to show the new admin interface?

### Mockups

**Ticket Priority Overview**
![Image](https://github.com/zammad/zammad/assets/5445094/a8b8d130-9306-417e-9fce-9bd1b943f816)

_Ticket Priority Actions_
![Image](https://github.com/zammad/zammad/assets/5445094/52fbe62e-1705-4c59-8c03-a050debccd9b)

**Ticket Priority Add/Edit**

We need to clarify how we should handle the UI-Color and UI-Icon:
![Image](https://github.com/zammad/zammad/assets/5445094/2d413aa4-7fc2-45a7-8555-8bf7ba1a9e2d)

```[tasklist]
### Tasks
- [x] Add ticket priority management screen (DV)
- [x] Add a mechanism to hide the admin navigation links (DV)
- [x] Add a mechanism to display management links in object manager screen (DV)
- [x] Add clone action (DK)
- [x] Implement set default for new tickets action (DV)
- [x] Align the action with state implementation (DV)
- [x] Add note texts to `UI` attributes (DV)
- [x] Hide `ui_icon` in case `ui_color` is not set (DV)
- [x] Hide set default action in case of default records (DV)
- [x] Tests (DV)
```

**Comment by mgruner** [comment]
Review was successful, with minor suggestions. Can we close this already, @dvuckovic?

**Comment by dvuckovic** [comment]
We have some failing tests connected to the new controller. I'd like to address those first, stay tuned.
