### ISSUE TITLE
Possibility to add the user avatar inside the signature

### ISSUE THREAD

**Issue by dominikklein** [zammad/zammad#4926]
### What

It's not possible to add the user avatar inside the signature. With this, it's not possible to send a picture of the current agent when answering tickets.

### Use cases

The company philosophy is to be very personal, so the picture from the current agent should be present in the signature when answering customer requests.

### Intended Outcome

The possibility to place the current user avatar inside the signature.

### Technical Implementation

It should be possible to use such a variable inside the signature (and maybe in general for the variable replacement):

`#{user.avatar(100,100)}`

The params 100 and 100 are the height and width.

Results in `<img src="http://bild-url.de/image.png" width="100" height="100">` (or base64).
```[tasklist]
### Tasks
- [x] Add handling for new variable inside backend renderer - FL
- [x] Add handling for new variable in frontend replace tags handling - DK
- [x] Add new variable also inside variable suggestion inside the frontend (`::`)
- [x] Review
```
