### ISSUE TITLE
Zammad should not write to the var/ folder

### ISSUE THREAD

**Issue by mgruner** [zammad/zammad#5022]
Assignees: @mgruner @mantas 

### Used Zammad Version

6.2

### Environment

- Installation method: any
- Operating system: any
- Database + version: any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

When Zammad receives an email that cannot be processed, it will be stored in `var/spool/unprocessable_mails`. This is the only part of Zammad which still requires write FS access to that folder.

### Expected behaviour

Zammad should not write persistent data to the local file system. This will improve scalability and help with containerized deployments. See for example https://github.com/zammad/zammad-helm/pull/243

### Steps to reproduce the behaviour

Send an invalid mail to Zammad.

### I'm sure this is a bug and no feature request or a general question.

no
```[tasklist]
### Tasks
- [x] Add new model (MM)
- [x] Change storage and processing of unprocessable mails (MM)
- [x] Update places referring to unprocessable mails like Health Check (MM)
- [x] Add rails commands (MG)
- [x] Add migration for existing unprocessable mails files (MM)
- [x] ~~Add expiration based clean-up mechanism~~
- [x] Remove the var folder from the codebase (check for references e.g. in older migrations)
- [x] Enhance previous migration file
- [ ] Early UAT with second level, especially about rails commands signature
```

**Comment by mgruner** [comment]
We will probably need to refine this one for a way forward.

Here are the historic use cases that I know of. We probably should check if they still apply.

### Historic Use Cases for Unprocessable Mails Handling

- Incoming mails should not be lost without informing the sender
- This should be valid even if the database is not available (comment: this particular one seems to be inappropriate to me now)
- The administrator should have a possibility to look at the mails and modify them to make them processable by Zammad
- It should be possible to re-try the mail import

Side note: Currently about 90% of malformed mails are SPAM, according to our experience. 10% are Zammad issues (parsing MIME issues or ticket processing issues).

**Comment by mgruner** [comment]
# Discussion 2024-02-06

## Acceptance Critieria

- Admin must be able to view, modify, reprocess or delete the unprocessable mails (via CLI, similar to the way it is currently done).
- Mails should not be saved in the FS by default.
- Verify that in case of a database issue (unavailability) the incoming email is not discarded from the server - this is probably already the case. (May not be possible with POP3)

## Implementation Proposal

- Unprocessable mails are stored in the database directly or via the storage provider layer of Zammad. This can be decided by the implementing team. The simplest solution should be preferred. Database storage space does not really matter here as we don't talk about much data.
- All places using information about unprocessable mails like the health check or the reprocessing method need to be updated to check the new storage location instead.
- New rails commands should be added
  - to save all stored unprocessable mails to a transient folder for review, e.g. tmp/unprocessable_mail
  - to delete stored unprocessable mails from the storage
  - to update unprocessable mails from one or more files (if possible) or from a directory, writing the new state back to the storage
  - to call the mail reprocessing from a command rather than the API directly - reprocessing will only look at the storage, not at the temporary directory
  - command signatures should be negotiated with @t-shehab to ensure operations will stay efficient
- A migration should move any files present in `var/spool/unprocessable_mail` to the storage (`var` folder will be absent on new systems)
- Remove the `var` folder from the codebase

**Comment by mgruner** [comment]
Technical note: Zammad commands currently can only accept a fixed amount of arguments. So the update/delete commands cannot be called with a wildcard expanding to several arguments. Instead, they could accept either a file or perhaps a directory as argument, where all files found in the directory might be processed. Other ideas welcome. :D

**Comment by mgruner** [comment]
Related #5047
