### ISSUE TITLE
Subscribe/Unsubscribe from Multiple Tickets at once

### ISSUE THREAD

**Issue by Mirtaaa** [zammad/zammad#5135]
Assignees: @mgruner @dominikklein @vBenTec 

### WHAT
A) When I have a big amount of subscribed tickets, I have to cycle every singe ticket one by one to unsubscribe. That is very time consuming.

B) When I have a big amount of unsubscribed tickets, I have to cycle every singe ticket one by one to subscribe. That is very time consuming.

### USE CASE
A) If I am mentioned in a ticket I will automatically be subscribed to it. Over time a lot of tickets pile up in my view and make it hard to keep an overview, making it less helpful than a normal search.
Even If I can bulk-re-assign the tickets to somebody else, and clean up my view with it, I will still be bombarded with notfications.

B) If I have a lot of new/unassigned ticktes, I want to be able to subscribe to multiple tickets in which I won't be asigned but need/want  to stay up to date.

### EXPECTED BEHAVIOUR
- Mark multiple Tickets and Subscribe/ unsubscribe from all of them at once

### ACCEPTANCE CRITERIA
- I want to be able to manually subscribe/unsubscribe from multiple tickets at once

Depending on complexity: 
- I want to be able to subscribe/unsubscribe via trigger/scheduler

### IDEAS FOR SOLUTION
- Solve over the Overview Drag-and-Drop Macros

### FEEDBACK
- Solution over Scheduler would be great
- it would be enough to have an "Unsubscribe All" action
```[tasklist]
### Tasks
- [x] Extend Macro edit screen
- [x] Extend bulk macro execution logic
- [x] Bulk macro execution tests
- [x] Extend ticket zoom macro execution logic (MG)
- [x] Ticket zoom macro execution tests (BS)
- [x] (scheduler tasks, TBD)...
```

**Comment by MattSharp** [comment]
Just ran into this same issue but at least as a workaround I've altered the 'Subscribed' overview to only show tickets that are not closed or merged, not sure if this helps til this gets looked at. Brought my count down from 176 to 14

**Comment by dominikklein** [comment]
The idea is to have subscribe/unsubscribe values below the ticket area with the following values:

Subscribe: Current User, Specific User
Unsubscribe: Current User, Specific User, All Users
