### ISSUE TITLE
WhatsApp Feedback - 24h Window Reminder Message / Emoji-Reactions

### ISSUE THREAD

**Issue by Mirtaaa** [zammad/zammad#5224]
Assignees: @dvuckovic @fliebe92 @tschaefer 

### 1. Make Reminder Message Texts editable
About the reminder Message that is sent out 1h before the 24h window closes.

**Actual Behaviour:**
A Fixed Message is being sent out 1h before the 24h window closes.

**Expected Behaviour:**
I want to be able to change the Reminder Message Texts.

**Use Cases:**
Some Customers are being talked to in a formal way, some in an informal way.
Some Customers need different languages.

#### Implementation

Add an optional Reminder Message field to the WhatsApp channel configuration. The field will be empty by default, but contain the built-in reminder messages as a *placeholder*. If the Automatic Reminder toggle is switched off, the new field will be hidden from the screen, to declutter it a bit.

### 2. Emoji-Reactions
**Actual Behaviour:**
When a customer uses reactions on messages (emojis by pressing and holding on the message), this reaction is not displayed in Zammad

**Use Case:**
A customer gets a yes or no question (or a positive or negative question) and answers this with a reaction to the message, the agent will not receive this reaction and the communication will fail and cause misunderstandings.

#### Implementation

Add a badge to the article bubble that displays the customer's reaction, and make sure it's updated on all supported events (create/update/delete). Introduce a notification to agents about the reaction, so they can be informed in a timely fashion about the update, and include a link to the related article. Also, add a history entry for each reaction and removal of that reaction, with a reference to the related article.

---

<details>
  <summary>No Implementation</summary>

### 3. Make Reminder Message 'Interval' Information Visible
About the reminder Message that is sent out 1h before the 24h Windows closes.

**Actual Behaviour:**
I can only see some description in the document when this reminder is sent out, so I can not know until it happens the first time.

**Expected Behaviour:**
I want to be able to read somewhere that the message is being sent out 1h before the 24h-Window closes (e.g. channel configuration)

**NOTE:** This is basically solved:
https://admin-docs.zammad.org/en/latest/channels/whatsapp/limitations.html
The link to the documentation is included in the admin channel configuration, but this is not pertinent information for agents.

### 4. Make Reminder Message Numbers and Intervals configurable
I want to be able to configure how many Reminder Messages are being sent
I want to be able to configure when they are being sent

 **Use Case:**
 I want to send one message 3 Hours before, one message 1h before and 1 Message a minute before to say, that the 24h 
 the window has expired.
</details>

---

```[tasklist]
### Tasks
- [x] Add customizable reminder message to the WhatsApp channel config - DV
- [x] Adjust the documentation link for WhatsApp channel limitations (route change) - DV
- [x] Add display of reaction to the article bubble in all three frontends - DV
- [x] Add custom notification type for both online & email notifications on reactions - DV
- [x] Store the reaction author name in the article preferences and use it in the notification instead of the `to` field - TS
- [x] Add custom history entry on both adding and removing reaction events - TS
- [x] Implement reaction part in WhatsApp backend - TS/FL
- [x] Add tests - TS/FL
```
