### ISSUE TITLE
Improve checklist visibility in ticket context

### ISSUE THREAD

**Issue by dominikklein** [zammad/zammad#5336]
Assignees: @mantas @vBenTec @mgruner @dvuckovic 

### Problem

Currently, it's not easily visible that a checklist is present inside the ticket when you do not have the checklist sidebar open. The badge with the open count is not very well visible.
Also when all items are "done" it's no longer visible that a checklist is present inside the ticket.

Another problem is that in referenced tickets no information is visible that this ticket is used inside a checklist.

### Intended Outcome

Enhance the checklist visibility inside the ticket without entering the ticket checklist sidebar.

Enhance the navigation between linked tickets. Users should be able to easily return to the original ticket from any referenced ticket.

#### Implementation

- Add checklist progress indicator to the ticket header (e.g. `Checked 1 of 4`)
  - Shows current number of completed (!) items compared to number of total items, incl. ticket checklist items (e.g. `1 of 4`)
  - Click opens the checklist sidebar (unless it's already open)
  - The indicator will be hidden in case there is no ticket checklist or the checklist is completed
- Add indicator in referenced tickets to the ticket header (e.g. `Tracked in 2 tickets`)
  - Shows the ticket(s) where the current ticket is referenced as a checklist item
  - If referenced only in one ticket, the indicator shows the parent ticket's ticket hook (e.g. `Tracked in Ticket#1112345`)
  - If referenced in two or more tickets, the indicator shows the count of parent tickets
    - Click (+ hover in legacy desktop app) shows a popover with the list of parent ticket states/titles, with links to them
  - If the user has no access to the referencing ticket, that ticket will not be listed in the indicator/popover
  - If there are no referencing tickets (incl. because of lack of access to them), the indicator will be hidden

#### Mockups
<a href="https://github.com/user-attachments/assets/5785f8a6-1c01-4d5a-9d78-93e38a7f0f7c" target="_blank"><img width="180" alt="Tracked in #1112345" src="https://github.com/user-attachments/assets/5785f8a6-1c01-4d5a-9d78-93e38a7f0f7c"></a> <a href="https://github.com/user-attachments/assets/d0fd17eb-bb41-4e22-ba81-56d41303c395" target="_blank"><img width="180" alt="Checked 1 of 4 & Tracked in 2 tickets" src="https://github.com/user-attachments/assets/d0fd17eb-bb41-4e22-ba81-56d41303c395"></a>

```[tasklist]
### Tasks
- [x] Update checklist icon in the desktop view (BS)
- [x] Check current architecture for fetching the needed data (MM, MG)
- [x] Add model support for counting references (MM)
- [x] Extend ticketChecklist query to include data for the current ticket's checklist as well as any referencing checklists (MG)
- [x] Change Checklist::ItemType to use TicketReferenceType (MG)
- [x] Add missing policies and gql type authorization to checklists and checklist items (MG)
- [x] refactor subscription and add referenced_items handling (MG)
- [x] Extend checklist controller to include references data (MM)
- [x] ~Add simple caching, if needed~
- [x] Change data propagation in old tech stack if needed
- [x] Display ticket checklist information in top header in the new desktop app (BS)
- [x] New desktop app component tests (BS)
- [x] Display ticket checklist information in top header in the legacy app
- [x] Bring back removed_checklist field to make subscription work again (MG)
- [x] Rename field to ticketChecklist again in the subscription, and drop the referencingTickets field (MG)
- [x] Extend the checklist type with total and completed count (MG)
- [x] Trigger subscription also on group_id changes (MM)
- [x] Modify referencing tickets backend model function (MM)
- [x] Filter out inaccessible tickets from referencingTickets field, so that we don't need the TicketReference field there (MG)
- [x] Checklist query does not return referencingTickets, but directly the checklist type
- [x] Move the referencingTickets field to the ticket type (referencingChecklistTickets)
- [x] Add checklist field to the ticket type
- [x] Triggering of the ticket subscription in case of referencing checklist changes
- [x] Filter out inaccessible referencing tickets in legacy app (MM)
- [x] Add tests for the new fields on the ticket type (MG)
- [x] Inaccessible referenced ticket shows up if it's assets are leaked in other places (e.g. ActivityStream) (MM)
- [ ] Checklist on-the-fly deletion handling in old stack
```
