### ISSUE TITLE
Improve heavy used admin objects with pagination and search in admin interface

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#5384]
### User Story

As an admin I want to be able to comfortable and quickly navigate in the admin interface even though I have a large number of items created/configured. This needs to be possible in at least the sections of Users, Groups, Roles, Organizations, Overviews, Text modules, Macros and Templates.

### Actual behaviour

Currently, there are issues on customers systems with the pagination of users. Also, if you have like 500 groups it is hard to maintain them via the admin interface. Consulting also experienced issues with maintenance on text modules in the admin interface. It might make sense to improve heavy used admin objects with a search bar and pagination tools.

#### Pagination / search bar changes

Global Search Details → Search
* Should get improved with pagination

Admin → Users
* Should get improved with pagination

Admin → Groups
* Should get improved with search bar

Admin → Roles
* Should get improved with search bar

Admin → Organizations
* Should get improved with search bar

Admin → Overviews
* Should get improved with search bar

Admin → Text Modules
* Should get improved with search bar

Admin → Macros
* Should get improved with search bar

Admin → Templates
* Should get improved with search bar

#### Pagination

Pagination should get modified to the following style:

`1 2 3 [4] 5 6 > 500`

**Note: This will only affect the old tech stack. The new tech stack will stick to the infinity scroll idea.**

### Steps to reproduce the behaviour

.

### Support Ticket

Ticket#10164477
Ticket#10165576

### I'm sure this is a bug and no feature request or a general question.

no
```[tasklist]
### Tasks
- [x] Model Role needs to be indexable (ES)
- [x] Model Overview needs to be indexable (ES)
- [x] Model TextModule needs to be indexable (ES)
- [x] Model Macro needs to be indexable (ES)
- [x] Model Templates needs to be indexable (ES)
- [x] add search route for app/controllers/roles_controller.rb with model_search_render
- [x] add search route for app/controllers/overviews_controller.rb with model_search_render
- [x] add search route for app/controllers/text_modules_controller.rb with model_search_render
- [x] add search route for app/controllers/macros_controller.rb with model_search_render
- [x] add search route for app/controllers/templates_controller.rb with model_search_render
- [x] add search field support on app/assets/javascripts/app/controllers/_application_controller/table.coffee
- [x] add new pagination style support in general OR admin interface only (depending on how it works for ticket overview which is not included for all of this)
- [x] app/controllers/application_controller/renders_models.rb must support new **model_search_render** which implements default search for model (search + total count)
- [x] CONSIDER add filter support to App.ControllerTable. This would allow add a list of filterable roles for the Admin -> Users screen
- [x] app/models/user/search.rb must return total count of search or consider replace with model_search_render
- [x] app/models/ticket/search.rb must return total count of search or consider replace with model_search_render
- [x] Fix/Prevent issue that admin users can not sort by secondary organizations
- [x] Fix issue that oveviews are not sortable anymore (conflict with pagination and search). Maybe only allow drag and drop when it is only one page and for pagination style we go with a field in overview like for object attributes
- [x] Check if there are tests for role_ids/group_ids/ids in user/search.rb
- [x] Check if there are tests for ids in organization/search.rb
- [x] app/models/knowledge_base/search.rb must return total count of search or consider replace with model_search_render
- [x] Add test for model_search_render
- [x] Migrate rubocop:disable comments to todo.yml
- [x] Add capybara test for search bar
- [x] Add capybara test which checks that the drag and drop feature gets removed in admin overviews when a pagination arrives
- [x] Add capybara test that checks if the search bar string stays after reload
- [x] Reduce entries per page to 50 in admin interface
- [x] Add capybara test for search + pagination
- [x] Add model tests for pagination+search+offset+limit of the can_search.rb (ES+DB)
- [x] Rework global detail search to use the total count and pagination
```
