### ISSUE TITLE
Wrong type of table column after migrating from MariaDB to PostgreSQL

### ISSUE THREAD

**Issue by MarkusHeld** [zammad/zammad#5409]
### Used Zammad Version

6.3

### Environment

- Installation method: possible any
- Operating system: possible any 
- Database + version:  psql (PostgreSQL) 13.16 (Debian 13.16-0+deb11u1)

### Actual behaviour

When migrating a MariaDB database to Postgresql, the email_address column in the smime_certificates table is saved with an incorrect type. 

**The following type is set for the column email_addresses in the table smime_certificates in a clean Zammad posgresql system.**

```
email_addresses    | character varying[]
```

**but when I do a migration from a MariaDB to postgresql according to our documentation, the following type is set**

https://docs.zammad.org/en/pre-release/appendix/migrate-to-postgresql.html

```
email_addresses    | text[]
```

**The pgloader program used to migrate the database contains the following entry**

```
$ rake zammad:db:pgloader > /tmp/pgloader-command
```

```
AFTER LOAD DO
 $$ alter table smime_certificates alter column email_addresses type text[] using translate(email_addresses::text, '[]', '{}')::text[] $$,
 $$ alter table pgp_keys alter column email_addresses type text[] using translate(email_addresses::text, '[]', '{}')::text[] $$,
 $$ alter table public_links alter column screen type text[] using translate(screen::text, '[]', '{}')::text[] $$
```

**However, if the type of the email_addresses field is text, the following error is displayed when verifying an S/MIME certificate. This means the S/MIME integration does not work and must be deactivated.**

```
[1] pry(main)> SMIMECertificate.find_by_email_address('foobar').first
ActiveRecord::StatementInvalid: PG::UndefinedFunction: ERROR:  operator does not exist: text[] && character varying[]
LINE 1: ..." WHERE ((("smime_certificates"."email_addresses" && ARRAY['...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

from /opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:894:in `exec_params'
Caused by PG::UndefinedFunction: ERROR:  operator does not exist: text[] && character varying[]
LINE 1: ..." WHERE ((("smime_certificates"."email_addresses" && ARRAY['...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

from /opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:894:in `exec_params'
```

### Expected behaviour

After a migration from MariaDB to Postgresql the S/Mime integration still works in Zammad.

### Steps to reproduce the behaviour

1. Install a system with MySQL/MariaDB backend.
2. Migrate to PostgreSQL by following [the official instructions](https://docs.zammad.org/en/latest/appendix/migrate-to-postgresql.html) (make sure to use `pgloader` utility for DB migration).
3. Run `SMIMECertificate.find_by_email_address('foobar').first` in your Rails console to trigger the error.

### Support Ticket

Ticket#10164132

### I'm sure this is a bug and no feature request or a general question.

yes

```[tasklist]
### Tasks
- [x] Change column array type to `varchar[]` in `pgloader` script
- [x] Add DB migration to update wrong column types on affected systems
- [x] Extend migration to include multi select and multi treeselect dynamic array columns in addition to static ones
- [x] Tests, tests, tests (DB migration, MySQL/MariaDB simulated migration, `pgloader` script)
```

**Comment by dvuckovic** [comment]
Can be triggered also for `pgp_keys.email_addresses` column via the following Rails console command:

```
[1] pry(main)> PGPKey.find_all_by_uid('foobar').first
ActiveRecord::StatementInvalid: PG::UndefinedFunction: ERROR:  operator does not exist: text[] && character varying[]
LINE 1: ... "pgp_keys" WHERE ((("pgp_keys"."email_addresses" && ARRAY['...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.

from ~/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:894:in `exec_params'
Caused by PG::UndefinedFunction: ERROR:  operator does not exist: text[] && character varying[]
LINE 1: ... "pgp_keys" WHERE ((("pgp_keys"."email_addresses" && ARRAY['...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.

from ~/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:894:in `exec_params'
```

Although the `pgloader-command` script refers to `public_links.screen` column as well, I was not able to trigger any errors via the standard Zammad interface. However, any exotic query might still be able to trigger a similar error message:

```
[2] pry(main)> PublicLink.where(SqlHelper.new(object: PublicLink).array_contains_one('screen', 'login')).first
ActiveRecord::StatementInvalid: PG::UndefinedFunction: ERROR:  operator does not exist: text[] && character varying[]
LINE 1: ...M "public_links" WHERE ((("public_links"."screen" && ARRAY['...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.

from ~/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:894:in `exec_params'
Caused by PG::UndefinedFunction: ERROR:  operator does not exist: text[] && character varying[]
LINE 1: ...M "public_links" WHERE ((("public_links"."screen" && ARRAY['...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.

from ~/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:894:in `exec_params'
```

**Comment by dvuckovic** [comment]
Also applies to any multi select and multi treeselect object attribute columns.
